Repository ReactiveX/RxJava, pull requests merged in 2018-09, with the labels that each got.

#6197 #6195 Fix Flowable.reduce(BiFunction) JavaDoc
  src/main/java/io/reactivex/Flowable.java
Labels: 2.x, Documentation

#6193 Add "error handling" java docs section to from callable & co
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6200 2.x: Fix toFlowable marbles and descriptions
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#6199 Fix terminology of cancel/dispose in the JavaDocs
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6205 2.x: Assert instead of print Undeliverable in some tests
  src/test/java/io/reactivex/maybe/MaybeCreateTest.java
  src/test/java/io/reactivex/maybe/MaybeTest.java
  src/test/java/io/reactivex/observers/SerializedObserverTest.java
  src/test/java/io/reactivex/subscribers/SerializedSubscriberTest.java
Labels: 2.x, Cleanup, Test

#6220 2.x JavaDocs: Remove unnecessary 's' from ConnectableObservable
  src/main/java/io/reactivex/observables/ConnectableObservable.java
Labels: 2.x, Cleanup, Documentation

#6223 Fix typos
  README.md
Labels: 2.x, Documentation

#6232 2.x: Cleanup Observable.flatMap drain logic
  src/main/java/io/reactivex/internal/operators/observable/ObservableFlatMap.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableFlatMapTest.java
Labels: 2.x, Cleanup
