Repository ReactiveX/RxJava, pull requests merged in 2018-04, with the labels that each got.

#5942 Removed TERMINATED check in onNext
  src/main/java/io/reactivex/processors/PublishProcessor.java
  src/main/java/io/reactivex/subjects/PublishSubject.java
Labels: 2.x, Cleanup

#5948 Fix Observable javadoc (#5944)
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#5951 2.x: blockingX JavaDoc to mention wrapping of checked Exceptions
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#5952 AppendOnlyLinkedArrayList#forEachWhile is not breaking iteration properly
  src/main/java/io/reactivex/internal/util/AppendOnlyLinkedArrayList.java
  src/test/java/io/reactivex/internal/util/MiscUtilTest.java
Labels: 2.x, Bug

#5957 2.x: Add Single.ignoreElement, deprecate toCompletable
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Single.java
  src/test/java/io/reactivex/internal/operators/single/SingleMiscTest.java
Labels: 2.x, Cleanup, Documentation

#5960 Fix typo
  README.md
Labels: 2.x, Documentation

#5959 2.x: Fix some grammar mistakes
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableConcatMapCompletable.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableConcatMapCompletable.java
  src/main/java/io/reactivex/processors/ReplayProcessor.java
  src/test/java/io/reactivex/JavadocWording.java
Labels: 2.x, Cleanup, Documentation

#5966 2.x: Workaround for Objects.requireNonNull inserted by javac
  src/test/java/io/reactivex/processors/UnicastProcessorTest.java
Labels: 2.x, Cleanup

#5972 2.x: Fix Observable.concatMapSingle dropping upstream items
  src/main/java/io/reactivex/internal/operators/mixed/ObservableConcatMapSingle.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableConcatMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableConcatMapSingleTest.java
Labels: 2.x, Bug

#5975 2.x: Fix refCount() connect/subscribe/cancel deadlock
  src/main/java/io/reactivex/internal/operators/flowable/FlowableRefCount.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableRefCount.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRefCountTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java
Labels: 2.x, Bug

#5977 2.x: Maybe/Single Javadoc; annotation cleanup
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Single.java
  src/test/java/io/reactivex/JavadocWording.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableConcatMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableConcatMapSingleTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleConcatTest.java
Labels: 2.x, Cleanup, Documentation

#5978 2.x: Fix Flowable.take to route post-cancel errors to RxJavaPlugins.onError
  src/main/java/io/reactivex/internal/operators/flowable/FlowableTake.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableLimitTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableTakeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableTakeTest.java
Labels: 2.x, Cleanup

#5981 2.x: improve JavaDocs of the subscribeActual methods
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#5982 2.x: deprecate getValues() in Subjects/Processors
  src/main/java/io/reactivex/processors/AsyncProcessor.java
  src/main/java/io/reactivex/processors/BehaviorProcessor.java
  src/main/java/io/reactivex/subjects/AsyncSubject.java
  src/main/java/io/reactivex/subjects/BehaviorSubject.java
  src/test/java/io/reactivex/processors/SerializedProcessorTest.java
  src/test/java/io/reactivex/subjects/SerializedSubjectTest.java
Labels: 2.x, Deprecation

#5985 2.x: Small cleanups in the Scheduler class
  src/main/java/io/reactivex/Scheduler.java
Labels: 2.x, Cleanup

#5984 2.x: Add blockingSubscribe JavaDoc clarifications
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation
