Repository ReactiveX/RxJava, pull requests merged in 2018-05, with the labels that each got.

#5987 Add marble diagrams to a few Single.doOnX methods.
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#5992 Observable's javadoc cleanup
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Cleanup, Documentation

#5991 2.x: Fix switchMap to indicate boundary fusion
  src/main/java/io/reactivex/internal/operators/flowable/FlowableSwitchMap.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableSwitchMap.java
  src/test/java/io/reactivex/TestHelper.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableSwitchTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableSwitchTest.java
Labels: 2.x, Bug

#5996 2.x: Automatically publish the generated JavaDocs from CI
  .travis.yml
  gradle/push_javadoc.sh
Labels: 2.x, Build, Documentation

#5995 Implement 'toString' method for some Emitters
  src/main/java/io/reactivex/internal/operators/completable/CompletableCreate.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableCreate.java
  src/main/java/io/reactivex/internal/operators/maybe/MaybeCreate.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableCreate.java
  src/main/java/io/reactivex/internal/operators/single/SingleCreate.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableCreateTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableCreateTest.java
  src/test/java/io/reactivex/internal/operators/maybe/MaybeCreateTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableCreateTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleCreateTest.java
Labels: 2.x, Cleanup

#5986 2.x: Add refCount with count & disconnect timeout
  src/main/java/io/reactivex/flowables/ConnectableFlowable.java
  src/main/java/io/reactivex/observables/ConnectableObservable.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRefCountTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java
Labels: 2.x, Enhancement

#6003 Fix typo in documentation
  README.md
Labels: 2.x, Documentation

#5997 2.x: readme: mention 1.x eol; 2.x snapshot javadoc url
  README.md
Labels: 2.x, Documentation

#6005 2.x: Javadoc space cleanup
  build.gradle
  gradle/javadoc_cleanup.gradle
Labels: 2.x, Cleanup, Documentation

#5979 2.x: Add throttleLatest operator
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableThrottleLatest.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableThrottleLatest.java
  src/test/java/io/reactivex/ParamValidationCheckerTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableThrottleLatestTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableThrottleLatestTest.java
Labels: 2.x, Enhancement

#6002 2.x: Add MulticastProcessor
  src/main/java/io/reactivex/processors/MulticastProcessor.java
  src/test/java/io/reactivex/processors/MulticastProcessorTest.java
Labels: 2.x, Enhancement

#6010 2.x: Add assertValueSetOnly and assertValueSequenceOnly to TestObserver + TestSubscriber
  src/main/java/io/reactivex/observers/BaseTestConsumer.java
  src/test/java/io/reactivex/observers/TestObserverTest.java
  src/test/java/io/reactivex/subscribers/TestSubscriberTest.java
Labels: 2.x, Enhancement

#6017 2.x: benchmark (0..1).flatMap, andThen & flattenAs performance
  src/jmh/java/io/reactivex/BinaryFlatMapPerf.java
Labels: 2.x, Performance

#6019 2.x: Fix Single.takeUntil, Maybe.takeUntil dispose behavior
  src/main/java/io/reactivex/internal/operators/maybe/MaybeTakeUntilPublisher.java
  src/main/java/io/reactivex/internal/operators/single/SingleTakeUntil.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableAmbTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableTakeUntilTest.java
  src/test/java/io/reactivex/internal/operators/maybe/MaybeTakeUntilTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableTakeUntilTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleTakeUntilTest.java
Labels: 2.x, Bug

#6022 2.x: Add TCK for MulticastProcessor & {0..1}.flatMapPublisher
  src/test/java/io/reactivex/tck/CompletableAndThenPublisherTckTest.java
  src/test/java/io/reactivex/tck/MaybeFlatMapPublisherTckTest.java
  src/test/java/io/reactivex/tck/MulticastProcessorAsPublisherTckTest.java
  src/test/java/io/reactivex/tck/MulticastProcessorRefCountedTckTest.java
  src/test/java/io/reactivex/tck/MulticastProcessorTckTest.java
  src/test/java/io/reactivex/tck/SingleFlatMapFlowableTckTest.java
Labels: 2.x, Test

#6021 2.x: Single.flatMapPublisher full implementation
  src/main/java/io/reactivex/Single.java
  src/main/java/io/reactivex/internal/operators/single/SingleFlatMapPublisher.java
  src/test/java/io/reactivex/internal/operators/single/SingleFlatMapTest.java
Labels: 2.x, Enhancement, Performance

#6023 2.x: More time to BehaviorProcessor & Interval TCK tests
  src/test/java/io/reactivex/tck/BehaviorProcessorAsPublisherTckTest.java
  src/test/java/io/reactivex/tck/IntervalTckTest.java
Labels: 2.x, Test-Failures

#6024 2.x: Dedicated {Single|Maybe}.flatMap{Publisher|Observable} & andThen(Observable|Publisher) implementations
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Single.java
  src/main/java/io/reactivex/internal/operators/mixed/CompletableAndThenObservable.java
  src/main/java/io/reactivex/internal/operators/mixed/CompletableAndThenPublisher.java
  src/main/java/io/reactivex/internal/operators/mixed/MaybeFlatMapObservable.java
  src/main/java/io/reactivex/internal/operators/mixed/MaybeFlatMapPublisher.java
  src/main/java/io/reactivex/internal/operators/mixed/SingleFlatMapObservable.java
  src/test/java/io/reactivex/completable/CompletableTest.java
  src/test/java/io/reactivex/internal/operators/mixed/CompletableAndThenObservableTest.java
  src/test/java/io/reactivex/internal/operators/mixed/CompletableAndThenPublisherTest.java
  src/test/java/io/reactivex/internal/operators/mixed/MaybeFlatMapObservableTest.java
  src/test/java/io/reactivex/internal/operators/mixed/MaybeFlatMapPublisherTest.java
  src/test/java/io/reactivex/internal/operators/mixed/SingleFlatMapObservableTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleFlatMapTest.java
Labels: 2.x, Enhancement, Performance

#6029 2.x: Upgrade to Gradle 4.3.1, add TakeUntilPerf
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/jmh/java/io/reactivex/TakeUntilPerf.java
Labels: 2.x, Build, Performance

#6028 2.x: Improve Observable.takeUntil
  src/main/java/io/reactivex/internal/operators/observable/ObservableTakeUntil.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableTakeUntilTest.java
Labels: 2.x, Enhancement
