Repository ReactiveX/RxJava, pull requests merged in 2018-06, with the labels that each got.

#6031 2.x: Inline CompositeDisposable JavaDoc
  src/main/java/io/reactivex/disposables/CompositeDisposable.java
Labels: 2.x, Cleanup, Documentation

#6042 fix MulticastProcessor javadoc comment
  src/main/java/io/reactivex/processors/MulticastProcessor.java
Labels: 2.x, Documentation

#6026 Fix Flowable.blockingSubscribe is unbounded and can lead to OOME
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/internal/functions/Functions.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableBlockingSubscribe.java
  src/main/java/io/reactivex/internal/subscribers/BoundedSubscriber.java
  src/test/java/io/reactivex/exceptions/OnErrorNotImplementedExceptionTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableBlockingTest.java
  src/test/java/io/reactivex/internal/subscribers/BoundedSubscriberTest.java
Labels: 2.x, Enhancement

#6045 Fix check that would always be false
  src/main/java/io/reactivex/internal/operators/flowable/FlowableBlockingSubscribe.java
Labels: 2.x, Bug

#6047 2.x: Add the wiki pages as docs
  docs/Additional-Reading.md
  docs/Alphabetical-List-of-Observable-Operators.md
  docs/Async-Operators.md
  docs/Backpressure-(2.0).md
  docs/Backpressure.md
  docs/Blocking-Observable-Operators.md
  docs/Combining-Observables.md
  docs/Conditional-and-Boolean-Operators.md
  docs/Connectable-Observable-Operators.md
  docs/Creating-Observables.md
  docs/Error-Handling-Operators.md
  docs/Error-Handling.md
  docs/Filtering-Observables.md
  docs/Getting-Started.md
  docs/Home.md
  docs/How-To-Use-RxJava.md
  docs/How-to-Contribute.md
  docs/Implementing-Your-Own-Operators.md
  docs/Implementing-custom-operators-(draft).md
  docs/Mathematical-and-Aggregate-Operators.md
  docs/Observable-Utility-Operators.md
  docs/Observable.md
  docs/Parallel-flows.md
  docs/Phantom-Operators.md
  docs/Plugins.md
  docs/Problem-Solving-Examples-in-RxJava.md
  docs/README.md
  docs/Reactive-Streams.md
  docs/Scheduler.md
  docs/String-Observables.md
  docs/Subject.md
  docs/The-RxJava-Android-Module.md
  docs/Transforming-Observables.md
  docs/What's-different-in-2.0.md
  docs/Writing-operators-for-2.0.md
  docs/_Footer.md
  docs/_Sidebar.md
  docs/_Sidebar.md.md
Labels: 2.x, Documentation

#6049 Make it explicit that throttleWithTimout is an alias of debounce
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#6053 2.x: Add Maybe marble diagrams 06/21/a
  src/main/java/io/reactivex/Maybe.java
Labels: 2.x, Documentation

#6057 2.x: Use different wording on blockingForEach() JavaDocs
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#6054 2.x: Expand {X}Processor JavaDocs by syncing with {X}Subject docs
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/processors/AsyncProcessor.java
  src/main/java/io/reactivex/processors/BehaviorProcessor.java
  src/main/java/io/reactivex/processors/PublishProcessor.java
  src/main/java/io/reactivex/processors/ReplayProcessor.java
  src/main/java/io/reactivex/processors/UnicastProcessor.java
  src/main/java/io/reactivex/subjects/UnicastSubject.java
Labels: 2.x, Documentation

#6060 2.x: Fix concatMap{Single|Maybe} null emission on dispose race
  src/main/java/io/reactivex/internal/operators/mixed/FlowableConcatMapMaybe.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableConcatMapSingle.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableConcatMapMaybe.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableConcatMapSingle.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableConcatMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableConcatMapSingleTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableConcatMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableConcatMapSingleTest.java
Labels: 2.x, Bug

#6066 Fix links for Single class
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation
