Repository ReactiveX/RxJava, pull requests merged in 2018-07, with the labels that each got.

#6070 2.x: Adjust JavaDocs dl/dd entry stylesheet
  build.gradle
  gradle/stylesheet.css
Labels: 2.x, Cleanup, Documentation

#6074 Add marble diagram to the Single.never method
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6078 2.x: Add Maybe.hide() marble diagram
  src/main/java/io/reactivex/Maybe.java
Labels: 2.x, Documentation

#6076 Add marble diagrams to the Single.delay method
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6079 2.x: Add Completable.takeUntil(Completable) operator
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/internal/operators/completable/CompletableTakeUntilCompletable.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableTakeUntilTest.java
Labels: 2.x, Enhancement

#6077 Add marble diagram for Single.hide operator
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6080 2.x: Improve class Javadoc of Single, Maybe and Completable
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6083 2.x: Add Completable marble diagrams (07/17a)
  src/main/java/io/reactivex/Completable.java
Labels: 2.x, Documentation

#6081 Add marble diagrams for Single.repeat operators
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6085 2.x: More Completable marbles (+18), add Completable.fromMaybe
  src/main/java/io/reactivex/Completable.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableFromMaybeTest.java
Labels: 2.x, Documentation, Enhancement

#6084 Add marble diagram for Single.repeatUntil operator
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6087 Add marbles for Single.from operators
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6086 Single error operators marbles
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6090 2.x: Add missing Completable marbles (+17, 07/18a)
  src/main/java/io/reactivex/Completable.java
Labels: 2.x, Documentation

#6091 Add marbles for Single.amb operators
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6096 2.x: Improve Completable.delay operator internals
  src/main/java/io/reactivex/internal/operators/completable/CompletableDelay.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableDelayTest.java
Labels: 2.x, Cleanup, Performance

#6098 2.x: Several more Completable marbles (7/19b)
  src/main/java/io/reactivex/Completable.java
Labels: 2.x, Documentation

#6103 2.x: Fix Completable mergeX JavaDoc missing dt before dd
  src/main/java/io/reactivex/Completable.java
Labels: 2.x, Cleanup

#6117 2.x: Update Readme.md about the parallel() operator
  README.md
Labels: 2.x, Documentation

#6116 6108 changed README to use Gradle's implementation instead of compile
  README.md
Labels: 2.x, Documentation
