Repository ReactiveX/RxJava, pull requests merged in 2018-10, with the labels that each got.

#6234 Add timeout and unit to TimeoutException message
  src/main/java/io/reactivex/internal/observers/BlockingMultiObserver.java
  src/main/java/io/reactivex/internal/observers/FutureObserver.java
  src/main/java/io/reactivex/internal/observers/FutureSingleObserver.java
  src/main/java/io/reactivex/internal/operators/completable/CompletableTimeout.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableTimeoutTimed.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableTimeoutTimed.java
  src/main/java/io/reactivex/internal/operators/single/SingleTimeout.java
  src/main/java/io/reactivex/internal/subscribers/FutureSubscriber.java
  src/main/java/io/reactivex/internal/util/ExceptionHelper.java
  src/test/java/io/reactivex/internal/observers/BlockingMultiObserverTest.java
  src/test/java/io/reactivex/internal/observers/FutureObserverTest.java
  src/test/java/io/reactivex/internal/observers/FutureSingleObserverTest.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableTimeoutTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableTimeoutTests.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableTimeoutTests.java
  src/test/java/io/reactivex/internal/operators/single/SingleTimeoutTest.java
  src/test/java/io/reactivex/internal/subscribers/FutureSubscriberTest.java
Labels: 2.x, Enhancement

#6236 2.x: Adjust Undeliverable & OnErrorNotImpl message to use full inner exception
  src/main/java/io/reactivex/exceptions/OnErrorNotImplementedException.java
  src/main/java/io/reactivex/exceptions/UndeliverableException.java
Labels: 2.x, Cleanup

#6241 2.x Wiki: Remove mention of i.r.f.Functions
  docs/What's-different-in-2.0.md
Labels: 2.x, Documentation

#6244 Add Nullable annotations for blocking methods in Completable
  src/main/java/io/reactivex/Completable.java
Labels: 2.x, Cleanup

#6242 Add delaySubscription() methods to Completable #5081
  src/main/java/io/reactivex/Completable.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableDelayTest.java
  src/test/java/io/reactivex/validators/ParamValidationCheckerTest.java
Labels: 2.x, Enhancement

#6252 2.x: Expand and fix Completable.delaySubscription tests
  src/test/java/io/reactivex/internal/operators/completable/CompletableDelaySubscriptionTest.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableDelayTest.java
Labels: 2.x, Cleanup, Test

#6257 2.x: Add Completable.delaySubscription marble, fix some javadoc
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/internal/fuseable/ConditionalSubscriber.java
Labels: 2.x, Documentation

#6260 Add generate examples to Creating-Observables.md in Wiki
  docs/Creating-Observables.md
Labels: 2.x, Documentation

#6262 Use JUnit's assert format for assert messages to enable better suppor…
  src/main/java/io/reactivex/observers/BaseTestConsumer.java
  src/test/java/io/reactivex/observers/TestObserverTest.java
Labels: 2.x, Test

#6258 2.x: Fix cancel/dispose upon upstream switch for some operators
  src/main/java/io/reactivex/internal/operators/flowable/FlowableConcatArray.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableConcatMap.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableDelaySubscriptionOther.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableOnErrorNext.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableRepeat.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableRepeatUntil.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableRepeatWhen.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableRetryBiPredicate.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableRetryPredicate.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableSwitchIfEmpty.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableTimeout.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableTimeoutTimed.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableConcatMap.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableRepeatWhen.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableRetryBiPredicate.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableRetryPredicate.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableRetryWhen.java
  src/main/java/io/reactivex/internal/subscriptions/SubscriptionArbiter.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableConcatMapTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableConcatTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRepeatTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRetryTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRetryWithPredicateTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableSwitchIfEmptyTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableConcatMapTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableConcatTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRepeatTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRetryTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRetryWithPredicateTest.java
  src/test/java/io/reactivex/internal/subscriptions/SubscriptionArbiterTest.java
Labels: 2.x, Shortcoming

#6267 2.x: Update Creating Observables docs
  docs/Creating-Observables.md
Labels: 2.x, Documentation

#6269 2.x: Call the doOn{Dispose|Cancel} handler at most once
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/internal/observers/DisposableLambdaObserver.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableDoOnLifecycle.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableDoOnLifecycleTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableDoOnUnsubscribeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableCacheTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableDoOnUnsubscribeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableReplayTest.java
Labels: 2.x, Shortcoming

#6273 Fix broken markdown
  docs/How-to-Contribute.md
Labels: 2.x, Documentation

#6266 2.x: Update Error Handling Operators docs
  docs/Error-Handling-Operators.md
Labels: 2.x, Documentation
