Repository ReactiveX/RxJava, pull requests merged in 2018-03, with the labels that each got.

#5871 2.x: Add Flowable.concatMapCompletable{DelayError} operator
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableConcatMapCompletable.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableConcatMapCompletableTest.java
Labels: 2.x, Enhancement

#5870 2.x: Add Flowable.switchMapCompletable{DelayError} operator
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapCompletable.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapCompletableTest.java
Labels: 2.x, Enhancement

#5872 2.x: Add Flowable.concatMap{Maybe,Single}{DelayError} operators
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableConcatMapMaybe.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableConcatMapSingle.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableConcatMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableConcatMapSingleTest.java
Labels: 2.x, Enhancement

#5873 2.x: Add Flowable.switchMap{Maybe,Single}{DelayError} operators
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapMaybe.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapSingle.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapSingleTest.java
Labels: 2.x, Enhancement

#5876 2.x: Add note about NoSuchElementException to Single.zip().
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#5883 2.x: Improve coverage and fix small mistakes/untaken paths in operators
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableFlatMap.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableReduceSeedSingle.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableReplay.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableWindowBoundary.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableWindowBoundarySelector.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableWindowBoundarySupplier.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableWindowTimed.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableInternalHelper.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableReduceSeedSingle.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableWindowBoundarySelector.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableWindowBoundarySupplier.java
  src/main/java/io/reactivex/internal/schedulers/InstantPeriodicTask.java
  src/main/java/io/reactivex/internal/schedulers/ScheduledDirectPeriodicTask.java
  src/main/java/io/reactivex/internal/schedulers/SchedulerWhen.java
  src/main/java/io/reactivex/internal/subscribers/QueueDrainSubscriber.java
  src/main/java/io/reactivex/processors/BehaviorProcessor.java
  src/main/java/io/reactivex/subjects/BehaviorSubject.java
  src/test/java/io/reactivex/internal/observers/BlockingMultiObserverTest.java
  src/test/java/io/reactivex/internal/observers/DisposableLambdaObserverTest.java
  src/test/java/io/reactivex/internal/observers/FullArbiterObserverTest.java
  src/test/java/io/reactivex/internal/observers/QueueDrainObserverTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableReduceTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRefCountTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableReplayTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableSingleTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableWindowWithFlowableTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableWindowWithStartEndFlowableTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableWindowWithTimeTest.java
  src/test/java/io/reactivex/internal/operators/maybe/MaybeMergeTest.java
  src/test/java/io/reactivex/internal/operators/maybe/MaybeSwitchIfEmptySingleTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableBufferTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableHideTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableInternalHelperTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableReduceTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableTakeLastOneTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableWindowWithObservableTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableWindowWithStartEndObservableTest.java
  src/test/java/io/reactivex/internal/schedulers/ExecutorSchedulerDelayedRunnableTest.java
  src/test/java/io/reactivex/internal/schedulers/InstantPeriodicTaskTest.java
  src/test/java/io/reactivex/internal/schedulers/SchedulerWhenTest.java
  src/test/java/io/reactivex/internal/subscribers/QueueDrainSubscriberTest.java
  src/test/java/io/reactivex/processors/BehaviorProcessorTest.java
  src/test/java/io/reactivex/subjects/BehaviorSubjectTest.java
Labels: 2.x, Bug, Cleanup, Coverage

#5886 2.x: Upgrade the algorithm of Observable.timeout(time|selector) operators
  src/main/java/io/reactivex/internal/disposables/ObserverFullArbiter.java
  src/main/java/io/reactivex/internal/observers/FullArbiterObserver.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableTimeout.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableTimeoutTimed.java
  src/test/java/io/reactivex/internal/disposables/ObserverFullArbiterTest.java
  src/test/java/io/reactivex/internal/observers/FullArbiterObserverTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableTimeoutWithSelectorTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableTimeoutTests.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableTimeoutWithSelectorTest.java
Labels: 2.x, Enhancement

#5887 2.x: Fix window(Observable|Callable) upstream handling
  src/main/java/io/reactivex/internal/operators/observable/ObservableWindowBoundary.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableWindowBoundarySupplier.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableWindowWithObservableTest.java
Labels: 2.x, Bug

#5888 2.x: Fix Flowable.window(Publisher|Callable) upstream handling
  build.gradle
  src/main/java/io/reactivex/internal/operators/flowable/FlowableWindowBoundary.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableWindowBoundarySupplier.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableWindowWithFlowableTest.java
Labels: 2.x, Bug

#5889 2.x: Cleanup, coverage and related component fixes
  src/main/java/io/reactivex/internal/operators/flowable/FlowableConcatMapEager.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowablePublishMulticast.java
  src/main/java/io/reactivex/processors/UnicastProcessor.java
  src/main/java/io/reactivex/subjects/BehaviorSubject.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableMulticastTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowablePublishMulticastTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowablePublishTest.java
  src/test/java/io/reactivex/observers/ObserverFusion.java
  src/test/java/io/reactivex/processors/UnicastProcessorTest.java
  src/test/java/io/reactivex/subjects/UnicastSubjectTest.java
Labels: 2.x, Cleanup, Coverage

#5890 Added nullable annotations to subjects
  src/main/java/io/reactivex/subjects/AsyncSubject.java
  src/main/java/io/reactivex/subjects/BehaviorSubject.java
  src/main/java/io/reactivex/subjects/CompletableSubject.java
  src/main/java/io/reactivex/subjects/MaybeSubject.java
  src/main/java/io/reactivex/subjects/PublishSubject.java
  src/main/java/io/reactivex/subjects/ReplaySubject.java
  src/main/java/io/reactivex/subjects/SerializedSubject.java
  src/main/java/io/reactivex/subjects/UnicastSubject.java
Labels: 2.x, Cleanup

#5895 Fix buffer() documentation to correctly describe onError behaviour
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#5897 2.x: clarify dematerialize() and terminal items/signals
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#5892 2.x: Fix the extra retention problem in ReplaySubject
  src/main/java/io/reactivex/subjects/ReplaySubject.java
  src/test/java/io/reactivex/subjects/ReplaySubjectTest.java
Labels: 2.x, Shortcoming

#5900 2.x: Fix Observable.flatMap scalar maxConcurrency overflow
  src/main/java/io/reactivex/internal/operators/observable/ObservableFlatMap.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableConcatMapTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableFlatMapTest.java
Labels: 2.x, Bug

#5893 2.x: Fix Flowable.publish(-|Function) subscriber swap possible data loss
  src/main/java/io/reactivex/internal/operators/flowable/FlowablePublish.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowablePublishMulticast.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowablePublishTest.java
Labels: 2.x, Shortcoming

#5898 2.x: Fix excess item retention in the other replay components
  src/main/java/io/reactivex/internal/operators/flowable/FlowableReplay.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableReplay.java
  src/main/java/io/reactivex/processors/ReplayProcessor.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableReplayTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableReplayTest.java
  src/test/java/io/reactivex/processors/ReplayProcessorTest.java
Labels: 2.x, Shortcoming

#5904 2.x: Fix Flowable.singleOrError().toFlowable() not signalling NoSuchElementException
  src/main/java/io/reactivex/internal/operators/flowable/FlowableSingle.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableSingleMaybe.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableSingleSingle.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableSingleTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableSingleTest.java
Labels: 2.x, Bug

#5902 2.x: Perf measure of Flowable flatMap & flatMapCompletable
  build.gradle
  src/jmh/java/io/reactivex/FlowableFlatMapCompletablePerf.java
  src/jmh/java/io/reactivex/FlowableFlatMapCompletableSyncPerf.java
  src/jmh/java/io/reactivex/PerfAsyncConsumer.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableFlatMapCompletableTest.java
Labels: 2.x, Performance

#5905 2.x: Coverage improvements, logical fixes and cleanups 03/08
  src/main/java/io/reactivex/internal/operators/flowable/FlowableCache.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableFlattenIterable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableReplay.java
  src/main/java/io/reactivex/internal/operators/observable/ObservablePublish.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableCacheTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableFlattenIterableTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableReplayTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableObserveOnTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservablePublishTest.java
  src/test/java/io/reactivex/observers/SerializedObserverTest.java
  src/test/java/io/reactivex/subjects/SerializedSubjectTest.java
Labels: 2.x, Bug, Cleanup, Coverage

#5910 2.x: Improve coverage, fix operator logic 03/12
  src/main/java/io/reactivex/exceptions/CompositeException.java
  src/main/java/io/reactivex/internal/functions/ObjectHelper.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundarySupplier.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferTimed.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableDebounceTimed.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableBuffer.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableBufferBoundarySupplier.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableDebounceTimed.java
  src/main/java/io/reactivex/internal/operators/single/SingleTakeUntil.java
  src/main/java/io/reactivex/internal/util/MergerBiFunction.java
  src/test/java/io/reactivex/exceptions/CompositeExceptionTest.java
  src/test/java/io/reactivex/internal/functions/ObjectHelperTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableDebounceTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableUsingTest.java
  src/test/java/io/reactivex/internal/operators/maybe/MaybeFlatMapBiSelectorTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableBufferTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableDebounceTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableUsingTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleFlatMapTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleTakeUntilTest.java
  src/test/java/io/reactivex/internal/util/MergerBiFunctionTest.java
  src/test/java/io/reactivex/processors/ReplayProcessorTest.java
  src/test/java/io/reactivex/subscribers/TestSubscriberTest.java
Labels: 2.x, Cleanup, Coverage

#5914 2.x: Benchmark X-Map-Z operators
  src/jmh/java/io/reactivex/FlattenRangePerf.java
  src/jmh/java/io/reactivex/FlowableFlatMapCompletableAsyncPerf.java
  src/jmh/java/io/reactivex/MemoryPerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableConcatMapCompletablePerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableConcatMapMaybeEmptyPerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableConcatMapMaybePerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableConcatMapSinglePerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableFlatMapCompletablePerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableFlatMapMaybeEmptyPerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableFlatMapMaybePerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableFlatMapSinglePerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableSwitchMapCompletablePerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableSwitchMapMaybeEmptyPerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableSwitchMapMaybePerf.java
  src/jmh/java/io/reactivex/xmapz/FlowableSwitchMapSinglePerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableConcatMapCompletablePerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableConcatMapMaybeEmptyPerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableConcatMapMaybePerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableConcatMapSinglePerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableFlatMapCompletablePerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableFlatMapMaybeEmptyPerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableFlatMapMaybePerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableFlatMapSinglePerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableSwitchMapCompletablePerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableSwitchMapMaybeEmptyPerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableSwitchMapMaybePerf.java
  src/jmh/java/io/reactivex/xmapz/ObservableSwitchMapSinglePerf.java
Labels: 2.x, Performance

#5915 2.x: Optimize ObservableConcatMapCompletable
  src/main/java/io/reactivex/internal/operators/mixed/ObservableConcatMapCompletable.java
  src/test/java/io/reactivex/TestHelper.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableConcatMapCompletableTest.java
Labels: 2.x, Performance

#5918 2.x: Improve the scalar source performance of Observable.(concat|switch)MapX
  src/main/java/io/reactivex/internal/operators/maybe/MaybeToObservable.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableConcatMapCompletable.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableConcatMapMaybe.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableConcatMapSingle.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapCompletable.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapMaybe.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapSingle.java
  src/main/java/io/reactivex/internal/operators/mixed/ScalarXMapZHelper.java
  src/main/java/io/reactivex/internal/operators/single/SingleToObservable.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableConcatMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableConcatMapSingleTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapCompletableTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapSingleTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ScalarXMapZHelperTest.java
Labels: 2.x, Performance

#5919 2.x: Add fusion support to ObservableSwitchMap inner source
  src/jmh/java/io/reactivex/xmapz/ObservableSwitchMapCompletablePerf.java
  src/main/java/io/reactivex/internal/observers/DeferredScalarDisposable.java
  src/main/java/io/reactivex/internal/operators/completable/CompletableToObservable.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableSwitchMap.java
  src/main/java/io/reactivex/internal/operators/single/SingleToObservable.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableToObservableTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableSwitchTest.java
Labels: 2.x, Performance

#5923 2.x: Fix JavaDoc warnings of buffer(Publisher|Callable)
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Cleanup, Documentation

#5924 2.x: Update Single.flatMapPublisher marble
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#5925 Add @Nullable annotations to Processors
  src/main/java/io/reactivex/processors/AsyncProcessor.java
  src/main/java/io/reactivex/processors/BehaviorProcessor.java
  src/main/java/io/reactivex/processors/PublishProcessor.java
  src/main/java/io/reactivex/processors/ReplayProcessor.java
  src/main/java/io/reactivex/processors/SerializedProcessor.java
  src/main/java/io/reactivex/processors/UnicastProcessor.java
Labels: 2.x

#5926 2.x: Expand the Getting Started
  README.md
Labels: 2.x, Documentation

#5928 2.x: Fix concatMapSingle & concatMapMaybe dispose-cleanup crash
  src/main/java/io/reactivex/internal/operators/mixed/FlowableConcatMapMaybe.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableConcatMapSingle.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableConcatMapMaybe.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableConcatMapSingle.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableConcatMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableConcatMapSingleTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableConcatMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableConcatMapSingleTest.java
Labels: 2.x, Bug

#5930 Add @NonNull annotations to create methods of Subjects and Processors
  src/main/java/io/reactivex/processors/BehaviorProcessor.java
  src/main/java/io/reactivex/processors/PublishProcessor.java
  src/main/java/io/reactivex/processors/ReplayProcessor.java
  src/main/java/io/reactivex/processors/UnicastProcessor.java
  src/main/java/io/reactivex/subjects/AsyncSubject.java
  src/main/java/io/reactivex/subjects/BehaviorSubject.java
  src/main/java/io/reactivex/subjects/CompletableSubject.java
  src/main/java/io/reactivex/subjects/MaybeSubject.java
  src/main/java/io/reactivex/subjects/PublishSubject.java
  src/main/java/io/reactivex/subjects/ReplaySubject.java
  src/main/java/io/reactivex/subjects/UnicastSubject.java
Labels: 2.x

#5935 1.x: Fix take() to route late errors to RxJavaHooks
  src/main/java/rx/internal/operators/OperatorTake.java
  src/test/java/rx/internal/operators/OperatorTakeTest.java
Labels: 1.x, Bug
