Repository ReactiveX/RxJava, pull requests merged in 2018-02, with the labels that each got.

#5843 2.x: Expand the JavaDocs of the Scheduler API
  src/main/java/io/reactivex/Scheduler.java
  src/main/java/io/reactivex/schedulers/SchedulerRunnableIntrospection.java
Labels: 2.x, Documentation

#5844 2.x: Explain the properties of the XEmitter interfaces in detail
  src/main/java/io/reactivex/CompletableEmitter.java
  src/main/java/io/reactivex/FlowableEmitter.java
  src/main/java/io/reactivex/MaybeEmitter.java
  src/main/java/io/reactivex/ObservableEmitter.java
  src/main/java/io/reactivex/SingleEmitter.java
Labels: 2.x, Documentation

#5848 2.x: Improve the wording of the Maybe.fromCallable JavaDoc
  src/main/java/io/reactivex/Maybe.java
Labels: 2.x, Documentation

#5851 Fix a race condition in OperatorMerge.InnerSubscriber#onError
  src/main/java/rx/internal/operators/OperatorMerge.java
  src/test/java/rx/internal/operators/OperatorMergeTest.java
Labels: 1.x, Bug

#5850 Fix a race condition that may make OperatorMaterialize emit too many terminal notifications
  .travis.yml
  src/main/java/rx/internal/operators/OperatorMaterialize.java
  src/test/java/rx/internal/operators/OperatorMaterializeTest.java
Labels: 1.x, Bug

#5845 2.x: Add efficient concatWith(Single|Maybe|Completable) overloads
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableConcatWithCompletable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableConcatWithMaybe.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableConcatWithSingle.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableConcatWithCompletable.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableConcatWithMaybe.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableConcatWithSingle.java
  src/test/java/io/reactivex/InternalWrongNaming.java
  src/test/java/io/reactivex/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableConcatWithCompletableTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableConcatWithMaybeTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableConcatWithSingleTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableConcatWithCompletableTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableConcatWithMaybeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableConcatWithSingleTest.java
  src/test/java/io/reactivex/observable/ObservableNullTests.java
  src/test/java/io/reactivex/tck/ConcatWithCompletableTckTest.java
  src/test/java/io/reactivex/tck/ConcatWithMaybeEmptyTckTest.java
  src/test/java/io/reactivex/tck/ConcatWithMaybeTckTest.java
  src/test/java/io/reactivex/tck/ConcatWithSingleTckTest.java
Labels: 2.x, Enhancement

#5847 2.x: Add efficient mergeWith(Single|Maybe|Completable) overloads.
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableMergeWithCompletable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableMergeWithMaybe.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableMergeWithSingle.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableMergeWithCompletable.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableMergeWithMaybe.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableMergeWithSingle.java
  src/test/java/io/reactivex/InternalWrongNaming.java
  src/test/java/io/reactivex/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithCompletableTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithMaybeTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithSingleTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithCompletableTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithMaybeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithSingleTest.java
  src/test/java/io/reactivex/observable/ObservableNullTests.java
  src/test/java/io/reactivex/tck/MergeWithCompletableTckTest.java
  src/test/java/io/reactivex/tck/MergeWithMaybeEmptyTckTest.java
  src/test/java/io/reactivex/tck/MergeWithMaybeTckTest.java
  src/test/java/io/reactivex/tck/MergeWithSingleTckTest.java
Labels: 2.x, Enhancement

#5856 2.x: Add finite requirement to various collector operators JavaDoc
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#5860 2.x: Flowable.groupBy add overload with evicting map factory
  build.gradle
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableGroupBy.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableGroupByTest.java
Labels: 2.x, Enhancement

#5861 2.x: Fix Javadoc warnings, links to the JDK types
  build.gradle
  src/main/java/io/reactivex/CompletableObserver.java
  src/main/java/io/reactivex/MaybeObserver.java
  src/main/java/io/reactivex/Observer.java
  src/main/java/io/reactivex/SingleObserver.java
Labels: 2.x, Cleanup, Documentation

#5863 2.x: Expand the documentation of the Flowable.lift() operator
  src/main/java/io/reactivex/Flowable.java
Labels: 2.x, Documentation

#5867 2.x: enhance test for groupBy with evicting map factory
  src/test/java/io/reactivex/internal/operators/flowable/FlowableGroupByTest.java
Labels: 2.x, Test

#5865 2.x: Improve the JavaDoc of the other lift() operators
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation
