Repository ReactiveX/RxJava, pull requests merged in 2018-08, with the labels that each got.

#6125 Fixed broken link under RxJS in docs/Additional-Reading.md
  docs/Additional-Reading.md
Labels: 2.x, Cleanup, Documentation

#6095 Add marbles for Single.timer, Single.defer and Single.toXXX operators
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6121 2.x: Flowable.onErrorResumeNext improvements
  src/main/java/io/reactivex/internal/operators/flowable/FlowableOnErrorNext.java
  src/test/java/io/reactivex/flowable/FlowableNullTests.java
Labels: 2.x, Enhancement

#6128 2.x: Remove fromEmitter() in wiki
  docs/Creating-Observables.md
Labels: 2.x, Documentation

#6133 2.x: Update _Sidebar.md with new order of topics
  docs/_Sidebar.md
  docs/_Sidebar.md.md
Labels: 2.x, Documentation

#6135 Initial clean up for Combining Observables docs
  docs/Combining-Observables.md
Labels: 2.x, Documentation

#6131 2.x: Expand Creating-Observables.md wiki
  docs/Creating-Observables.md
Labels: 2.x, Discussion, Documentation

#6136 2.x: Update Getting started docs
  docs/Getting-Started.md
Labels: 2.x, Documentation

#6137 2.x: Add marbles for Single.concat operator
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6140 2.x: Update Mathematical and Aggregate Operators docs
  docs/Mathematical-and-Aggregate-Operators.md
Labels: 2.x, Documentation

#6141 Add marble diagrams for various Single operators
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6143 2.x: Add concatArrayEagerDelayError operator (expose feature)
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableConcatMapEagerTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableConcatMapEagerTest.java
  src/test/java/io/reactivex/validators/JavadocForAnnotations.java
Labels: 2.x, Documentation, Enhancement

#6145 2.x: Fix boundary fusion of concatMap and publish operator
  src/main/java/io/reactivex/internal/operators/flowable/FlowableConcatMap.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowablePublish.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableConcatMapTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowablePublishTest.java
Labels: 2.x, Bug

#6152 2.x: Clarify TestObserver.assertValueSet in docs and via tests
  src/main/java/io/reactivex/observers/BaseTestConsumer.java
  src/test/java/io/reactivex/observers/TestObserverTest.java
  src/test/java/io/reactivex/subscribers/TestSubscriberTest.java
Labels: 2.x, Documentation

#6155 2.x: Fix marble of Maybe.flatMap events to MaybeSource
  src/main/java/io/reactivex/Maybe.java
Labels: 2.x, Documentation

#6158 2.x: Make Flowable.fromCallable consistent with the other fromCallables
  src/main/java/io/reactivex/internal/operators/flowable/FlowableFromCallable.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableFromCallableTest.java
Labels: 2.x, Shortcoming

#6165 Error handle on Completable.fromCallable with RxJavaPlugins
  src/main/java/io/reactivex/internal/operators/completable/CompletableFromCallable.java
Labels: 2.x, Shortcoming

#6171 2.x: Add explanation text to Undeliverable & OnErrorNotImplemented exs
  src/main/java/io/reactivex/exceptions/OnErrorNotImplementedException.java
  src/main/java/io/reactivex/exceptions/UndeliverableException.java
  src/test/java/io/reactivex/exceptions/ExceptionsTest.java
Labels: 2.x, Enhancement

#6180 Update Additional-Reading.md
  docs/Additional-Reading.md
Labels: Documentation

#6187 2.x: Fix refCount termination-reconnect race
  src/main/java/io/reactivex/internal/disposables/ResettableConnectable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableRefCount.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableReplay.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableRefCount.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableReplay.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRefCountTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java
Labels: 2.x, Bug
