Repository ReactiveX/RxJava, pull requests merged in 2018-11, with the labels that each got.

#6275 2.x: Improve the Observable/Flowable cache() operators
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableCache.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableCache.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableCacheTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableReplayTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableCacheTest.java
Labels: 2.x, Enhancement, Performance

#6280 2.x: Improve the package docs of io.reactivex.schedulers
  src/main/java/io/reactivex/schedulers/package-info.java
Labels: 2.x, Documentation

#6283 2.x: Fix Observable.flatMap to sustain concurrency level
  src/main/java/io/reactivex/internal/operators/observable/ObservableFlatMap.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableFlatMapTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableFlatMapTest.java
Labels: 2.x, Bug

#6287 2.x: Expose the Keep-Alive value of the IO Scheduler as System property. (#6279)
  src/main/java/io/reactivex/internal/schedulers/IoScheduler.java
  src/main/java/io/reactivex/schedulers/Schedulers.java
Labels: 2.x, Enhancement

#6278 2.x: Add materialize() and dematerialize()
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Single.java
  src/main/java/io/reactivex/internal/operators/completable/CompletableMaterialize.java
  src/main/java/io/reactivex/internal/operators/maybe/MaybeMaterialize.java
  src/main/java/io/reactivex/internal/operators/mixed/MaterializeSingleObserver.java
  src/main/java/io/reactivex/internal/operators/single/SingleDematerialize.java
  src/main/java/io/reactivex/internal/operators/single/SingleMaterialize.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableMaterializeTest.java
  src/test/java/io/reactivex/internal/operators/maybe/MaybeMaterializeTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleDematerializeTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleMaterializeTest.java
Labels: 2.x, Discussion, Enhancement

#6281 2.x: Add dematerialize(selector), deprecate old
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableDematerialize.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableDematerialize.java
  src/test/java/io/reactivex/flowable/FlowableTests.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableDematerializeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableDematerializeTest.java
  src/test/java/io/reactivex/observable/ObservableTest.java
Labels: 2.x, Discussion, Enhancement

#6291 2.x: Update Transforming Observables docs
  docs/Transforming-Observables.md
Labels: 2.x, Documentation

#6305 Javadoc : Explain explicitly about using Emitter interface methods synchronously
  src/main/java/io/reactivex/Emitter.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#6308 Javadoc updates for RXJava Issue 6289
  src/main/java/io/reactivex/Flowable.java
Labels: 2.x, Documentation

#6311 Javadoc: explain that distinctUntilChanged requires non-mutating data to work as expected
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#6321 Fix Flowable#toObservable backpressure support
  src/main/java/io/reactivex/Flowable.java
Labels: 2.x, Documentation
