Repository ReactiveX/RxJava, pull requests merged in 2019-06, with the labels that each got.

#6497 Update Alphabetical-List-of-Observable-Operators.md
  docs/Alphabetical-List-of-Observable-Operators.md
Labels: Cleanup, Documentation

#6498 3.x: Merge in changes from 2.x since the initial branching
  README.md
  docs/Additional-Reading.md
  docs/Alphabetical-List-of-Observable-Operators.md
  docs/Creating-Observables.md
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
  src/main/java/io/reactivex/disposables/CompositeDisposable.java
  src/main/java/io/reactivex/internal/operators/completable/CompletableFromAction.java
  src/main/java/io/reactivex/internal/operators/completable/CompletableFromRunnable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableFromArray.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableRefCount.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableSamplePublisher.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableFromArray.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableRefCount.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableSampleWithObservable.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableZip.java
  src/main/java/io/reactivex/processors/package-info.java
  src/main/java/io/reactivex/subjects/package-info.java
  src/test/java/io/reactivex/completable/CompletableTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableZipTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableZipTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleMiscTest.java
  src/test/java/io/reactivex/maybe/MaybeTest.java
Labels: 3.x, Bug, Cleanup, Documentation

#6504 2.x: Fix javadocs & imports
  gradle/javadoc_cleanup.gradle
  src/main/java/io/reactivex/processors/package-info.java
  src/main/java/io/reactivex/schedulers/Schedulers.java
  src/test/java/io/reactivex/internal/operators/maybe/MaybeDoOnTerminateTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleDoOnTerminateTest.java
Labels: 2.x, Cleanup, Documentation

#6499 Null check for BufferExactBoundedObserver
  src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferTimed.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableBufferTimed.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableBufferTest.java
Labels: 2.x, Bug

#6506 2.x: Expand the Javadoc of Flowable
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#6507 3.x: Sync up with 2.2.10 snapshot
  CHANGES.md
  docs/What's-different-in-3.0.md
  gradle/javadoc_cleanup.gradle
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferTimed.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableBufferTimed.java
  src/main/java/io/reactivex/processors/package-info.java
  src/main/java/io/reactivex/schedulers/Schedulers.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java
  src/test/java/io/reactivex/internal/operators/maybe/MaybeDoOnTerminateTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableBufferTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleDoOnTerminateTest.java
Labels: 3.x, Bug, Cleanup

#6510 2.x: Correct Reactive-Streams to Reactive Streams in Documentation
  DESIGN.md
  README.md
  docs/What's-different-in-2.0.md
  docs/Writing-operators-for-2.0.md
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/FlowableSubscriber.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
  src/main/java/io/reactivex/exceptions/ProtocolViolationException.java
  src/main/java/io/reactivex/internal/subscribers/StrictSubscriber.java
  src/main/java/io/reactivex/package-info.java
Labels: 2.x, Cleanup, Documentation

#6514 3.x: Merge as() into to()
  docs/What's-different-in-3.0.md
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/CompletableConverter.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/FlowableConverter.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/MaybeConverter.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/ObservableConverter.java
  src/main/java/io/reactivex/Single.java
  src/main/java/io/reactivex/SingleConverter.java
  src/main/java/io/reactivex/parallel/ParallelFlowable.java
  src/main/java/io/reactivex/parallel/ParallelFlowableConverter.java
  src/test/java/io/reactivex/ConverterTest.java
  src/test/java/io/reactivex/completable/CompletableTest.java
  src/test/java/io/reactivex/flowable/FlowableConversionTest.java
  src/test/java/io/reactivex/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/flowable/FlowableTests.java
  src/test/java/io/reactivex/maybe/MaybeTest.java
  src/test/java/io/reactivex/observable/ObservableNullTests.java
  src/test/java/io/reactivex/observable/ObservableTest.java
  src/test/java/io/reactivex/observers/ObserverFusion.java
  src/test/java/io/reactivex/parallel/ParallelFlowableTest.java
  src/test/java/io/reactivex/single/SingleNullTests.java
  src/test/java/io/reactivex/single/SingleTest.java
  src/test/java/io/reactivex/subscribers/SubscriberFusion.java
Labels: 3.x, Cleanup, Enhancement

#6516 3.x: remove getValues() from some subjects/processors
  src/main/java/io/reactivex/processors/AsyncProcessor.java
  src/main/java/io/reactivex/processors/BehaviorProcessor.java
  src/main/java/io/reactivex/subjects/AsyncSubject.java
  src/main/java/io/reactivex/subjects/BehaviorSubject.java
  src/test/java/io/reactivex/processors/SerializedProcessorTest.java
  src/test/java/io/reactivex/subjects/SerializedSubjectTest.java
Labels: 3.x, Cleanup, Removal

#6517 3.x: Various small API changes and removals
  src/jmh/java/io/reactivex/BlockingGetPerf.java
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
  src/main/java/io/reactivex/internal/observers/BlockingMultiObserver.java
  src/test/java/io/reactivex/completable/CompletableTest.java
  src/test/java/io/reactivex/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/internal/observers/BlockingMultiObserverTest.java
  src/test/java/io/reactivex/internal/observers/LambdaObserverTest.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableAwaitTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableIgnoreElementsTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableIgnoreElementsTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleMiscTest.java
  src/test/java/io/reactivex/internal/subscribers/LambdaSubscriberTest.java
  src/test/java/io/reactivex/maybe/MaybeTest.java
  src/test/java/io/reactivex/observable/ObservableNullTests.java
  src/test/java/io/reactivex/schedulers/FailOnBlockingTest.java
  src/test/java/io/reactivex/validators/ParamValidationCheckerTest.java
Labels: 3.x, Cleanup, Removal

#6519 3.x: ConnectableFlowable/ConnetableObservabe redesign
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/flowables/ConnectableFlowable.java
  src/main/java/io/reactivex/internal/disposables/ResettableConnectable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowablePublish.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableRefCount.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableReplay.java
  src/main/java/io/reactivex/internal/operators/observable/ObservablePublish.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableRefCount.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableReplay.java
  src/main/java/io/reactivex/observables/ConnectableObservable.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowablePublishTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRefCountTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservablePublishTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java
  src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
Labels: 3.x, Enhancement

#6522 2.x: Fix concatMapDelayError not continuing on fused inner source crash
  src/main/java/io/reactivex/internal/operators/flowable/FlowableConcatMap.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableConcatMapTest.java
Labels: 2.x, Bug

#6525 3.x: remove `test` from `testXXX` method names, create a validator
  src/test/java/io/reactivex/validators/TestPrefixInMethodName.java
Labels: 3.x, Cleanup, Test

#6523 3.x: Fix concatMapDelayError not continuing on fused inner source crash
  src/main/java/io/reactivex/internal/operators/flowable/FlowableConcatMap.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableConcatMapTest.java
Labels: 3.x, Bug

#6530 3.x: disambiguate startWith+1 to startWithItem & startWithIterable
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/test/java/io/reactivex/flowable/FlowableCovarianceTest.java
  src/test/java/io/reactivex/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/flowable/FlowableStartWithTests.java
  src/test/java/io/reactivex/flowable/FlowableTests.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableCombineLatestTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeDelayErrorTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRetryTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableWindowWithSizeTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableWindowWithTimeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableCombineLatestTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableMergeDelayErrorTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRetryTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableWindowWithSizeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableWindowWithTimeTest.java
  src/test/java/io/reactivex/observable/ObservableCovarianceTest.java
  src/test/java/io/reactivex/observable/ObservableNullTests.java
  src/test/java/io/reactivex/observable/ObservableStartWithTests.java
  src/test/java/io/reactivex/observable/ObservableTest.java
Labels: 3.x, Cleanup

#6531 3.x: add marbles to X.fromSupplier
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
Labels: 3.x, Documentation

#6533 3.x: Remove Changes.md
  CHANGES.md
Labels: 3.x, Cleanup, Removal

#6535 3.x: JavaDocs: clarify create emitters are per consumer
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
Labels: 3.x, Documentation

#6534 3.x: Make using() resource disposal order consistent with eager-mode
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
  src/main/java/io/reactivex/internal/operators/completable/CompletableUsing.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableUsing.java
  src/main/java/io/reactivex/internal/operators/maybe/MaybeUsing.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableUsing.java
  src/main/java/io/reactivex/internal/operators/single/SingleUsing.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableUsingTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableUsingTest.java
  src/test/java/io/reactivex/internal/operators/maybe/MaybeUsingTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableUsingTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleUsingTest.java
Labels: 3.x, Enhancement

#6537 3.x: Promote Beta/Experimental to Standard
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
  src/main/java/io/reactivex/internal/operators/completable/CompletableMaterialize.java
  src/main/java/io/reactivex/internal/operators/maybe/MaybeMaterialize.java
  src/main/java/io/reactivex/internal/operators/mixed/MaterializeSingleObserver.java
  src/main/java/io/reactivex/internal/operators/single/SingleDematerialize.java
  src/main/java/io/reactivex/internal/operators/single/SingleMaterialize.java
  src/main/java/io/reactivex/schedulers/Schedulers.java
  src/test/java/io/reactivex/validators/TestPrefixInMethodName.java
Labels: 3.x, API promotion

#6538 3.x: Add concatMap with Scheduler guaranteeing where the mapper runs
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableConcatMapScheduler.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableConcatMapScheduler.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableConcatMapSchedulerTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableConcatTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableConcatMapSchedulerTest.java
Labels: 3.x, Enhancement

#6539 3.x: remove no-arg dematerialize(); remove replay(Scheduler) variants
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableInternalHelper.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableReplay.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableInternalHelper.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableReplay.java
  src/test/java/io/reactivex/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableDematerializeTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableReplayEagerTruncateTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableReplayTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableDematerializeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableReplayEagerTruncateTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableReplayTest.java
  src/test/java/io/reactivex/observable/ObservableNullTests.java
Labels: 3.x, Removal

#6544 Fixing version tag on Schedulers.from(Executor, boolean)
  src/main/java/io/reactivex/schedulers/Schedulers.java
Labels: 3.x, Cleanup

#6546 2.x: Simplify JUnit tests with more appropriate assert methods
  src/test/java/io/reactivex/NotificationTest.java
  src/test/java/io/reactivex/completable/CompletableTest.java
  src/test/java/io/reactivex/exceptions/OnNextValueTest.java
  src/test/java/io/reactivex/flowable/FlowableMergeTests.java
  src/test/java/io/reactivex/flowable/FlowableNotificationTest.java
  src/test/java/io/reactivex/internal/operators/flowable/BlockingFlowableLatestTest.java
  src/test/java/io/reactivex/internal/operators/flowable/BlockingFlowableMostRecentTest.java
  src/test/java/io/reactivex/internal/operators/flowable/BlockingFlowableNextTest.java
  src/test/java/io/reactivex/internal/operators/flowable/BlockingFlowableToFutureTest.java
  src/test/java/io/reactivex/internal/operators/flowable/BlockingFlowableToIteratorTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableOnBackpressureBufferTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableUnsubscribeOnTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableLatestTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableMostRecentTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableNextTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableToFutureTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableToIteratorTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableGroupByTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableUnsubscribeOnTest.java
  src/test/java/io/reactivex/internal/util/NotificationLiteTest.java
  src/test/java/io/reactivex/internal/util/VolatileSizeArrayListTest.java
  src/test/java/io/reactivex/observable/ObservableMergeTests.java
  src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
  src/test/java/io/reactivex/processors/ReplayProcessorTest.java
  src/test/java/io/reactivex/processors/UnicastProcessorTest.java
  src/test/java/io/reactivex/schedulers/AbstractSchedulerConcurrencyTests.java
  src/test/java/io/reactivex/schedulers/ComputationSchedulerTests.java
  src/test/java/io/reactivex/schedulers/TimedTest.java
  src/test/java/io/reactivex/schedulers/TrampolineSchedulerTest.java
  src/test/java/io/reactivex/subjects/ReplaySubjectTest.java
  src/test/java/io/reactivex/subjects/UnicastSubjectTest.java
Labels: 2.x, Cleanup, Test

#6549 3.x: Simplify JUnit tests with more appropriate assert methods
  src/test/java/io/reactivex/NotificationTest.java
  src/test/java/io/reactivex/completable/CompletableTest.java
  src/test/java/io/reactivex/exceptions/OnNextValueTest.java
  src/test/java/io/reactivex/flowable/FlowableMergeTests.java
  src/test/java/io/reactivex/flowable/FlowableNotificationTest.java
  src/test/java/io/reactivex/internal/operators/flowable/BlockingFlowableLatestTest.java
  src/test/java/io/reactivex/internal/operators/flowable/BlockingFlowableMostRecentTest.java
  src/test/java/io/reactivex/internal/operators/flowable/BlockingFlowableNextTest.java
  src/test/java/io/reactivex/internal/operators/flowable/BlockingFlowableToFutureTest.java
  src/test/java/io/reactivex/internal/operators/flowable/BlockingFlowableToIteratorTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableGroupByTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableOnBackpressureBufferTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableUnsubscribeOnTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableLatestTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableMostRecentTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableNextTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableToFutureTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableToIteratorTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableGroupByTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableUnsubscribeOnTest.java
  src/test/java/io/reactivex/internal/util/NotificationLiteTest.java
  src/test/java/io/reactivex/internal/util/VolatileSizeArrayListTest.java
  src/test/java/io/reactivex/observable/ObservableMergeTests.java
  src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
  src/test/java/io/reactivex/processors/ReplayProcessorTest.java
  src/test/java/io/reactivex/processors/UnicastProcessorTest.java
  src/test/java/io/reactivex/schedulers/AbstractSchedulerConcurrencyTests.java
  src/test/java/io/reactivex/schedulers/ComputationSchedulerTests.java
  src/test/java/io/reactivex/schedulers/TimedTest.java
  src/test/java/io/reactivex/schedulers/TrampolineSchedulerTest.java
  src/test/java/io/reactivex/subjects/ReplaySubjectTest.java
  src/test/java/io/reactivex/subjects/UnicastSubjectTest.java
Labels: 3.x, Cleanup, Test
