Repository ReactiveX/RxJava, pull requests merged in 2019-01, with the labels that each got.

#6353 2.x: Update README
  README.md
Labels: 2.x, Documentation

#6359 2.x: Fix the error/race in Observable.repeatWhen due to flooding repeat signal
  src/main/java/io/reactivex/internal/operators/observable/ObservableRepeatWhen.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRepeatTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRetryTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRepeatTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRetryTest.java
Labels: 2.x, Bug

#6362 2.x: Fix Completable.andThen(Completable) not running on observeOn scheduler.
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/internal/operators/completable/CompletableAndThenCompletable.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableAndThenCompletableabTest.java
  src/test/java/io/reactivex/internal/operators/completable/CompletableAndThenTest.java
Labels: 2.x, Shortcoming

#6364 2.x: Fix publish not requesting upon client change
  src/main/java/io/reactivex/internal/operators/flowable/FlowablePublish.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowablePublishTest.java
Labels: 2.x, Bug

#6371 2.x: Fix bounded replay() memory leak due to bad node retention
  src/main/java/io/reactivex/internal/operators/flowable/FlowableReplay.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableReplay.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableReplayTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableReplayTest.java
  src/test/java/io/reactivex/processors/ReplayProcessorTest.java
  src/test/java/io/reactivex/subjects/ReplaySubjectTest.java
Labels: 2.x, Bug

#6380 Fix bug in CompositeException.getRootCause
  src/main/java/io/reactivex/exceptions/CompositeException.java
  src/test/java/io/reactivex/exceptions/CompositeExceptionTest.java
Labels: 2.x, Bug

#6377 Expand `Observable#debounce` and `Flowable#debounce` javadoc
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#6386 Add doOnTerminate to Single/Maybe for consistency
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Single.java
  src/main/java/io/reactivex/internal/operators/maybe/MaybeDoOnTerminate.java
  src/main/java/io/reactivex/internal/operators/single/SingleDoOnTerminate.java
  src/test/java/io/reactivex/internal/operators/maybe/MaybeDoOnTerminateTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleDoOnTerminateTest.java
Labels: 2.x, Enhancement
