Repository ReactiveX/RxJava, pull requests merged in 2019-11, with the labels that each got.

#6700 3.x: Update javadoc for observeOn to mention its eagerness
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
Labels: 3.x, Documentation

#6699 Readme: Cherry-pick fixes from #6683, add ProGuard workaround entry
  README.md
Labels: 3.x, Documentation

#6704 2.x: Add ProGuard rule to avoid j.u.c.Flow warnings due to RS 1.0.3
  src/main/resources/META-INF/proguard/rxjava2.pro
Labels: 2.x, Android, Build

#6705 2.x: ProGuard R8 dont warn Flow* classes
  src/main/resources/META-INF/proguard/rxjava2.pro
Labels: 2.x, Android, Build

#6706 3.x: Embed R8 ProGuard rules to ignore Flow* interfaces in RS 1.0.3
  README.md
  src/main/resources/META-INF/proguard/rxjava3.pro
Labels: 3.x, Android, Build

#6708 3.x: Fix concurrent clear in observeOn while output-fused
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableObserveOn.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableObserveOn.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableObserveOnTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableObserveOnTest.java
Labels: 3.x, Bug

#6709 3.x: cleanup of some Javadoc parts
  src/test/java/io/reactivex/rxjava3/flowable/FlowableBackpressureTests.java
  src/test/java/io/reactivex/rxjava3/schedulers/AbstractSchedulerTests.java
  src/test/java/io/reactivex/rxjava3/schedulers/SchedulerTestHelper.java
Labels: 3.x, Cleanup

#6710 2.x: Fix concurrent clear in observeOn while output-fused
  src/main/java/io/reactivex/internal/operators/flowable/FlowableObserveOn.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableObserveOn.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableObserveOnTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableObserveOnTest.java
Labels: 2.x, Bug

#6711 3.x: Upgrade to Gradle 5.6.4
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: 3.x, Build

#6714 3.x: Fix MulticastProcessor not requesting more after limit is reached
  src/main/java/io/reactivex/rxjava3/processors/MulticastProcessor.java
  src/test/java/io/reactivex/rxjava3/processors/MulticastProcessorTest.java
Labels: 3.x, Bug

#6715 2.x: Fix MulticastProcessor not requesting more after limit is reached
  src/main/java/io/reactivex/processors/MulticastProcessor.java
  src/test/java/io/reactivex/processors/MulticastProcessorTest.java
Labels: 2.x, Bug

#6719 3.x: Fix parallel() on grouped flowable not replenishing properly
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupBy.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableObserveOnTest.java
Labels: 3.x, Bug

#6723 3.x: observeOn and Schedulers.from eagerness javadoc updates
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/schedulers/Schedulers.java
Labels: 3.x, Cleanup, Documentation

#6720 2.x: Fix parallel() on grouped flowable not replenishing properly
  src/main/java/io/reactivex/internal/operators/flowable/FlowableGroupBy.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableGroupByTest.java
Labels: 2.x, Bug

#6722 2.x: Update javadoc for observeOn to mention its eagerness
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Documentation

#6729 3.x: Fix self-see references, some comments
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/disposables/ActionDisposable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/BlockingFlowableMostRecent.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/BlockingObservableMostRecent.java
Labels: 3.x, Cleanup, Documentation

#6732 3.x: Update Single.zip marble diagrams (4 cases)
  src/main/java/io/reactivex/rxjava3/core/Single.java
Labels: 3.x, Documentation

#6730 3.x: Add Maybe marble diagrams (14 cases)
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
Labels: 3.x, Documentation
