Repository ReactiveX/RxJava, pull requests merged in 2019-03, with the labels that each got.

#6432 2.x composite disposable docs
  src/main/java/io/reactivex/disposables/CompositeDisposable.java
Labels: 2.x, Cleanup

#6434 2.x: Improve subjects and processors package doc
  src/main/java/io/reactivex/processors/package-info.java
  src/main/java/io/reactivex/subjects/package-info.java
Labels: 2.x, Cleanup, Documentation

#6433 Make error messages of parameter checks consistent
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Cleanup

#6436 refactor: improves Creating-Observables wiki doc
  docs/Creating-Observables.md
Labels: 2.x, Cleanup, Documentation

#6442 Undeliverable error handling logic for Completable operators
  src/main/java/io/reactivex/Completable.java
  src/main/java/io/reactivex/internal/operators/completable/CompletableFromAction.java
  src/main/java/io/reactivex/internal/operators/completable/CompletableFromRunnable.java
Labels: 2.x, Bug
