Repository ReactiveX/RxJava, pull requests merged in 2019-10, with the labels that each got.

#6662 3.x: Multiple empty line detection to ignore whitespace
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableTakeTest.java
  src/test/java/io/reactivex/rxjava3/validators/TooManyEmptyNewLines.java
Labels: 3.x, Cleanup

#6665 3.x: Add Reactive Programming on Android with RxJava to Additional Docs
  docs/Additional-Reading.md
Labels: Documentation

#6664 3.x: Fix groupBy group emission in some cases
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupBy.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableGroupBy.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableGroupByTest.java
Labels: 3.x, Bug

#6668 3.x: Add missing marble diagams to Single
  src/main/java/io/reactivex/rxjava3/core/Single.java
Labels: 3.x, Documentation

#6675 Add Export-Package declarations for OSGi headers
  build.gradle
Labels: 3.x, Build

#6676 3.x: Fix concurrent clear() calls when fused chains are canceled
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupBy.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureBuffer.java
  src/main/java/io/reactivex/rxjava3/processors/UnicastProcessor.java
  src/main/java/io/reactivex/rxjava3/subjects/UnicastSubject.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureBufferTest.java
  src/test/java/io/reactivex/rxjava3/processors/UnicastProcessorTest.java
  src/test/java/io/reactivex/rxjava3/subjects/UnicastSubjectTest.java
Labels: 3.x, Bug

#6677 2.x: Fix concurrent clear() calls when fused chains are canceled
  src/main/java/io/reactivex/internal/operators/flowable/FlowableGroupBy.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableOnBackpressureBuffer.java
  src/main/java/io/reactivex/processors/UnicastProcessor.java
  src/main/java/io/reactivex/subjects/UnicastSubject.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableGroupByTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableOnBackpressureBufferTest.java
  src/test/java/io/reactivex/processors/UnicastProcessorTest.java
  src/test/java/io/reactivex/subjects/UnicastSubjectTest.java
Labels: 2.x, Bug

#6674 3.x: Fix window(time) possible interrupts while terminating
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowTimed.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowTimed.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowWithTimeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowWithTimeTest.java
Labels: 3.x, Shortcoming

#6681 Backport marble diagrams for Single from 3.x
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6682 3.x: Fix type inference problem when compiling with newer JDKs
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
Labels: 3.x, Bug

#6684 2.x: Fix window(time) possible interrupts while terminating
  src/main/java/io/reactivex/internal/operators/flowable/FlowableWindowTimed.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableWindowTimed.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableWindowWithTimeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableWindowWithTimeTest.java
Labels: 2.x, Bug
