Repository ReactiveX/RxJava, pull requests merged in 2019-12, with the labels that each got.

#6739 3.x: Mockito fix deprecated API use after bump to 3.2.0
  src/test/java/io/reactivex/rxjava3/disposables/SequentialDisposableTest.java
  src/test/java/io/reactivex/rxjava3/disposables/SerialDisposableTests.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableDeferTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableFromCallableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableFromSupplierTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableDeferTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableFromCallableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableFromSupplierTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleFromCallableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleFromSupplierTest.java
Labels: 3.x, Cleanup, Test

#6741 3.x: Upgrade to Gradle 6.0.1
  gradle/wrapper/gradle-wrapper.properties
Labels: 3.x, Build

#6745 3.x: Make DisposableContainer public API
  src/main/java/io/reactivex/rxjava3/disposables/CompositeDisposable.java
  src/main/java/io/reactivex/rxjava3/disposables/DisposableContainer.java
  src/main/java/io/reactivex/rxjava3/internal/disposables/ListCompositeDisposable.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/NewThreadWorker.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/ScheduledRunnable.java
Labels: 3.x, API promotion

#6746 Javadoc cleanup 1203
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/disposables/ActionDisposable.java
  src/main/java/io/reactivex/internal/operators/flowable/BlockingFlowableMostRecent.java
  src/main/java/io/reactivex/internal/operators/observable/BlockingObservableMostRecent.java
Labels: 2.x, Cleanup, Documentation

#6740 3.x: Change Flowable.groupBy to signal MBE instead of possibly hanging
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupBy.java
  src/test/java/io/reactivex/rxjava3/flowable/FlowableGroupByTests.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableRetryTest.java
Labels: 3.x, Shortcoming

#6750 3.x: Update observeOn docs with links and +backpressure explanation
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
Labels: 3.x, Documentation

#6748 3.x: Change how the cause of CompositeException is generated
  src/main/java/io/reactivex/rxjava3/exceptions/CompositeException.java
  src/test/java/io/reactivex/rxjava3/exceptions/CompositeExceptionTest.java
Labels: 3.x, Shortcoming

#6752 3.x: Do not update snapshot Javadocs from secondary branches
  gradle/buildViaTravis.sh
  gradle/push_javadoc.sh
Labels: 3.x, Build

#6754 2.x: Zip, CombineLatest, and Amb operators throw when supplied with ObservableSource implementation that doesn't subclass Observable
  src/main/java/io/reactivex/internal/operators/observable/ObservableAmb.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableCombineLatest.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableZip.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableAmbTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableCombineLatestTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableZipTest.java
Labels: 2.x, Bug

#6756 3.x: Fix Observable amb, combineLatest & zip ArrayStoreException
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableAmb.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableCombineLatest.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableZip.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableAmbTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableAmbTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableCombineLatestTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableZipTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeAmbTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeZipIterableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableAmbTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableCombineLatestTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableZipTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleAmbTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleZipIterableTest.java
Labels: 3.x, Bug

#6758 3.x: Fix Flowable.window (size, time) cancellation and abandonment
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindow.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowTimed.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/WindowSubscribeIntercept.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowWithSizeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowWithTimeTest.java
Labels: 3.x, Shortcoming

#6761 3.x: Fix Observable.window (size & time) cancellation and abandonment
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindow.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowSubscribeIntercept.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowTimed.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindow.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowSubscribeIntercept.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowTimed.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowWithSizeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowWithTimeTest.java
Labels: 3.x, Shortcoming

#6762 3.x: Fix window (boundary, start/end) cancel and abandonment
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowBoundary.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowBoundarySelector.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowBoundary.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowBoundarySelector.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowWithFlowableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowWithStartEndFlowableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowWithObservableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowWithSizeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowWithStartEndObservableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowWithTimeTest.java
Labels: 3.x, Shortcoming

#6769 [3.x] Remove deprecated method from 2.x
  src/main/java/io/reactivex/rxjava3/internal/functions/ObjectHelper.java
  src/test/java/io/reactivex/rxjava3/internal/functions/ObjectHelperTest.java
Labels: 3.x, Cleanup

#6770 [3.x] Replace some ObjecsHelpers methods with Java 8 APIs
  src/main/java/io/reactivex/rxjava3/core/Notification.java
  src/main/java/io/reactivex/rxjava3/internal/functions/Functions.java
  src/main/java/io/reactivex/rxjava3/internal/functions/ObjectHelper.java
  src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeContains.java
  src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleEquals.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/TrampolineScheduler.java
  src/main/java/io/reactivex/rxjava3/internal/util/NotificationLite.java
  src/main/java/io/reactivex/rxjava3/observers/BaseTestConsumer.java
  src/main/java/io/reactivex/rxjava3/schedulers/TestScheduler.java
  src/main/java/io/reactivex/rxjava3/schedulers/Timed.java
  src/test/java/io/reactivex/rxjava3/internal/functions/ObjectHelperTest.java
  src/test/java/io/reactivex/rxjava3/testsupport/BaseTestConsumerEx.java
  src/test/java/io/reactivex/rxjava3/testsupport/TestHelper.java
Labels: 3.x, Cleanup, Java 8

#6773 Add FunctionalInterface annotations.
  src/main/java/io/reactivex/rxjava3/core/CompletableConverter.java
  src/main/java/io/reactivex/rxjava3/core/CompletableOnSubscribe.java
  src/main/java/io/reactivex/rxjava3/core/CompletableOperator.java
  src/main/java/io/reactivex/rxjava3/core/CompletableSource.java
  src/main/java/io/reactivex/rxjava3/core/CompletableTransformer.java
  src/main/java/io/reactivex/rxjava3/core/FlowableConverter.java
  src/main/java/io/reactivex/rxjava3/core/FlowableOnSubscribe.java
  src/main/java/io/reactivex/rxjava3/core/FlowableOperator.java
  src/main/java/io/reactivex/rxjava3/core/FlowableTransformer.java
  src/main/java/io/reactivex/rxjava3/core/MaybeConverter.java
  src/main/java/io/reactivex/rxjava3/core/MaybeOnSubscribe.java
  src/main/java/io/reactivex/rxjava3/core/MaybeOperator.java
  src/main/java/io/reactivex/rxjava3/core/MaybeSource.java
  src/main/java/io/reactivex/rxjava3/core/MaybeTransformer.java
  src/main/java/io/reactivex/rxjava3/core/ObservableConverter.java
  src/main/java/io/reactivex/rxjava3/core/ObservableOnSubscribe.java
  src/main/java/io/reactivex/rxjava3/core/ObservableOperator.java
  src/main/java/io/reactivex/rxjava3/core/ObservableSource.java
  src/main/java/io/reactivex/rxjava3/core/ObservableTransformer.java
  src/main/java/io/reactivex/rxjava3/core/SingleConverter.java
  src/main/java/io/reactivex/rxjava3/core/SingleOnSubscribe.java
  src/main/java/io/reactivex/rxjava3/core/SingleOperator.java
  src/main/java/io/reactivex/rxjava3/core/SingleSource.java
  src/main/java/io/reactivex/rxjava3/core/SingleTransformer.java
  src/main/java/io/reactivex/rxjava3/functions/Action.java
  src/main/java/io/reactivex/rxjava3/functions/BiConsumer.java
  src/main/java/io/reactivex/rxjava3/functions/BiFunction.java
  src/main/java/io/reactivex/rxjava3/functions/BiPredicate.java
  src/main/java/io/reactivex/rxjava3/functions/BooleanSupplier.java
  src/main/java/io/reactivex/rxjava3/functions/Cancellable.java
  src/main/java/io/reactivex/rxjava3/functions/Consumer.java
  src/main/java/io/reactivex/rxjava3/functions/Function.java
  src/main/java/io/reactivex/rxjava3/functions/Function3.java
  src/main/java/io/reactivex/rxjava3/functions/Function4.java
  src/main/java/io/reactivex/rxjava3/functions/Function5.java
  src/main/java/io/reactivex/rxjava3/functions/Function6.java
  src/main/java/io/reactivex/rxjava3/functions/Function7.java
  src/main/java/io/reactivex/rxjava3/functions/Function8.java
  src/main/java/io/reactivex/rxjava3/functions/Function9.java
  src/main/java/io/reactivex/rxjava3/functions/IntFunction.java
  src/main/java/io/reactivex/rxjava3/functions/LongConsumer.java
  src/main/java/io/reactivex/rxjava3/functions/Predicate.java
  src/main/java/io/reactivex/rxjava3/functions/Supplier.java
  src/main/java/io/reactivex/rxjava3/internal/fuseable/ScalarSupplier.java
  src/main/java/io/reactivex/rxjava3/parallel/ParallelFlowableConverter.java
  src/main/java/io/reactivex/rxjava3/parallel/ParallelTransformer.java
Labels: 3.x, Cleanup, Java 8

#6778 3.x: Javadocs package-info made nicer, update README regarding Java 8
  README.md
  src/main/java/io/reactivex/rxjava3/annotations/Nullable.java
  src/main/java/io/reactivex/rxjava3/annotations/package-info.java
  src/main/java/io/reactivex/rxjava3/disposables/package-info.java
  src/main/java/io/reactivex/rxjava3/exceptions/package-info.java
  src/main/java/io/reactivex/rxjava3/observers/package-info.java
  src/main/java/io/reactivex/rxjava3/subjects/package-info.java
  src/main/java/io/reactivex/rxjava3/subscribers/package-info.java
Labels: 3.x, Cleanup, Documentation

#6775 3.x: [Java 8] Implement mapOptional, collector, first/last/single stage
  build.gradle
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableCollectWithCollector.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableCollectWithCollectorSingle.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableFirstStageSubscriber.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableLastStageSubscriber.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableMapOptional.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableSingleStageSubscriber.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableStageSubscriber.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/CollectWithCollectorTckTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlowableCollectWithCollectorTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlowableMapOptionalTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlowableStageSubscriberOrDefaultTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlowableStageSubscriberOrErrorTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/MapOptionalTckTest.java
  src/test/java/io/reactivex/rxjava3/testsupport/TestHelper.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationCheckerTest.java
Labels: 3.x, Enhancement, Java 8

#6779 3.x: [Java 8] Add blockingStream & flatMapStream to Flowable
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableFlatMapStream.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableFromStream.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlatMapStream0HTckTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlatMapStream0TckTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlatMapStream1HTckTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlatMapStream1TckTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlatMapStream2HTckTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlatMapStream2TckTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlowableBlockingStreamTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlowableFlatMapStreamTest.java
  src/test/java/io/reactivex/rxjava3/testsupport/TestHelper.java
Labels: 3.x, Enhancement, Java 8

#6783 3.x: [Java 8] Add fromOpt/Stage, mapOptional, toCompletionStage to M/S/C
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/CompletableFromCompletionStage.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/CompletionStageConsumer.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/MaybeFromCompletionStage.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/MaybeMapOptional.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/SingleFromCompletionStage.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/SingleMapOptional.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/CompletableFromCompletionStageTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/CompletableToCompletionStageTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/MaybeFromCompletionStageTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/MaybeFromOptionalTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/MaybeMapOptionalTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/MaybeToCompletionStageTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/SingleFromCompletionStageTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/SingleMapOptionalTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/SingleToCompletionStageTest.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationCheckerTest.java
Labels: 3.x, Enhancement, Java 8

#6791 3.x: Add NonNull & SafeVarargs annotations + validator
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Notification.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableConcatMapEagerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableMergeDelayErrorTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableMergeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowablePublishFunctionTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeAmbTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeConcatArrayTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeMergeArrayTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeZipArrayTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeZipIterableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/ObservableConcatMapMaybeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/ObservableConcatMapSingleTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableAmbTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatMapEagerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatMapTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableZipTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleAmbTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleConcatTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleZipArrayTest.java
  src/test/java/io/reactivex/rxjava3/maybe/MaybeTest.java
  src/test/java/io/reactivex/rxjava3/observable/ObservableNullTests.java
  src/test/java/io/reactivex/rxjava3/single/SingleNullTests.java
  src/test/java/io/reactivex/rxjava3/validators/SourceAnnotationCheck.java
Labels: 3.x, Cleanup, Java 8

#6795 3.x: Add missing annotations, fix many diamonds
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/disposables/CompositeDisposable.java
  src/main/java/io/reactivex/rxjava3/disposables/SerialDisposable.java
  src/main/java/io/reactivex/rxjava3/exceptions/CompositeException.java
  src/main/java/io/reactivex/rxjava3/flowables/ConnectableFlowable.java
  src/main/java/io/reactivex/rxjava3/internal/functions/Functions.java
  src/main/java/io/reactivex/rxjava3/observables/ConnectableObservable.java
  src/main/java/io/reactivex/rxjava3/parallel/ParallelFlowable.java
  src/main/java/io/reactivex/rxjava3/processors/AsyncProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/BehaviorProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/FlowableProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/MulticastProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/PublishProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/ReplayProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/SerializedProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/UnicastProcessor.java
  src/main/java/io/reactivex/rxjava3/schedulers/TestScheduler.java
  src/main/java/io/reactivex/rxjava3/subjects/AsyncSubject.java
  src/main/java/io/reactivex/rxjava3/subjects/BehaviorSubject.java
  src/main/java/io/reactivex/rxjava3/subjects/CompletableSubject.java
  src/main/java/io/reactivex/rxjava3/subjects/MaybeSubject.java
  src/main/java/io/reactivex/rxjava3/subjects/PublishSubject.java
  src/main/java/io/reactivex/rxjava3/subjects/ReplaySubject.java
  src/main/java/io/reactivex/rxjava3/subjects/SerializedSubject.java
  src/main/java/io/reactivex/rxjava3/subjects/SingleSubject.java
  src/main/java/io/reactivex/rxjava3/subjects/Subject.java
  src/main/java/io/reactivex/rxjava3/subjects/UnicastSubject.java
  src/test/java/io/reactivex/rxjava3/core/ConverterTest.java
  src/test/java/io/reactivex/rxjava3/core/TransformerTest.java
  src/test/java/io/reactivex/rxjava3/flowable/FlowableConversionTest.java
  src/test/java/io/reactivex/rxjava3/internal/functions/FunctionsTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableCombineLatestTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableRetryTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableZipTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatMapEagerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableMergeDelayErrorTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableMergeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableRetryTest.java
  src/test/java/io/reactivex/rxjava3/maybe/MaybeTest.java
  src/test/java/io/reactivex/rxjava3/observable/ObservableNullTests.java
  src/test/java/io/reactivex/rxjava3/parallel/ParallelFlowableTest.java
  src/test/java/io/reactivex/rxjava3/parallel/ParallelReduceFullTest.java
  src/test/java/io/reactivex/rxjava3/parallel/ParallelSortedJoinTest.java
  src/test/java/io/reactivex/rxjava3/subjects/UnicastSubjectTest.java
  src/test/java/io/reactivex/rxjava3/testsupport/TestHelper.java
  src/test/java/io/reactivex/rxjava3/validators/BaseTypeAnnotations.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationNaming.java
  src/test/java/io/reactivex/rxjava3/validators/SourceAnnotationCheck.java
Labels: 3.x, Cleanup, Documentation, Java 8

#6799 3.x: XProcessor.offer to throw NPE immediately
  src/main/java/io/reactivex/rxjava3/processors/BehaviorProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/MulticastProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/PublishProcessor.java
  src/test/java/io/reactivex/rxjava3/processors/BehaviorProcessorTest.java
  src/test/java/io/reactivex/rxjava3/processors/MulticastProcessorTest.java
  src/test/java/io/reactivex/rxjava3/processors/PublishProcessorTest.java
Labels: 3.x, Cleanup

#6800 3.x: Add blockingForEach(Consumer, int) overload
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
Labels: 3.x, Enhancement

#6801 3.x: Add missing throwIfFatal calls
  src/main/java/io/reactivex/rxjava3/disposables/AutoCloseableDisposable.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableFlatMapStream.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/ObservableFlatMapStream.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableCollect.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableCollectSingle.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableDoOnEach.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableReplay.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableScalarXMap.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowBoundarySelector.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableZipIterable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFromFuture.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableBuffer.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableCollect.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableCollectSingle.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableReplay.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableScalarXMap.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowBoundarySelector.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/InstantPeriodicTask.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/ScheduledDirectPeriodicTask.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/SchedulerPoolFactory.java
  src/test/java/io/reactivex/rxjava3/disposables/DisposableTest.java
  src/test/java/io/reactivex/rxjava3/validators/CatchThrowIfFatalCheck.java
Labels: 3.x, Cleanup

#6805 3.x: [Java 8] Add flattenStreamAsX to Maybe/Single
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/MaybeFlattenStreamAsFlowable.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/MaybeFlattenStreamAsObservable.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/SingleFlattenStreamAsFlowable.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/SingleFlattenStreamAsObservable.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/MaybeFlattenStreamAsFlowableTckTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/MaybeFlattenStreamAsFlowableTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/MaybeFlattenStreamAsObservableTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/SingleFlattenStreamAsFlowableTckTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/SingleFlattenStreamAsFlowableTest.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/SingleFlattenStreamAsObservableTest.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocForAnnotations.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocWording.java
Labels: 3.x, Enhancement, Java 8

#6806 3.x: Prettify Flowable javadoc + validator
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocCodesAndLinks.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocWording.java
Labels: 3.x, Cleanup
