Repository ReactiveX/RxJava, pull requests merged in 2019-05, with the labels that each got.

#6480 Update README.md
  README.md
Labels: 2.x, Documentation

#6485 remove unused else from the Observable
  src/main/java/io/reactivex/Observable.java
Labels: 2.x, Cleanup

#6488 2.x: Fix zip not stopping the subscription upon eager error
  src/main/java/io/reactivex/internal/operators/observable/ObservableZip.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableZipTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableZipTest.java
Labels: 2.x, Bug
