Repository ReactiveX/RxJava, pull requests merged in 2019-08, with the labels that each got.

#6609 3.x: Fix refCount not resetting when termination triggers cross-cancel
  src/main/java/io/reactivex/internal/operators/flowable/FlowableRefCount.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableRefCount.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRefCountTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java
Labels: 3.x, Bug

#6616 3.x: Fix switchMap incorrect sync-fusion & error management
  src/main/java/io/reactivex/internal/operators/flowable/FlowableSwitchMap.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableSwitchMap.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableSwitchTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableSwitchTest.java
Labels: 3.x

#6618 2.x: Fix switchMap incorrect sync-fusion & error management
  src/main/java/io/reactivex/internal/operators/flowable/FlowableSwitchMap.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableSwitchMap.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableSwitchTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableSwitchTest.java
Labels: 2.x, Bug

#6627 2.x: Fix blockingIterable hang when force-disposed
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/internal/operators/flowable/BlockingFlowableIterable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableSwitchMap.java
  src/main/java/io/reactivex/internal/operators/observable/BlockingObservableIterable.java
  src/test/java/io/reactivex/internal/operators/flowable/BlockingFlowableToIteratorTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableNextTest.java
  src/test/java/io/reactivex/internal/operators/observable/BlockingObservableToIteratorTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableBufferTest.java
  src/test/java/io/reactivex/schedulers/TrampolineSchedulerTest.java
Labels: 2.x, Shortcoming

#6626 3.x: Fix blockingIterable not unblocking when force-disposed
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/BlockingFlowableIterable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/BlockingObservableIterable.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/BlockingFlowableToIteratorTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/BlockingObservableNextTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/BlockingObservableToIteratorTest.java
Labels: 3.x, Shortcoming

#6629 2.x: Fix refCount() not resetting when cross-canceled
  src/main/java/io/reactivex/internal/operators/flowable/FlowableRefCount.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableRefCount.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRefCountAltTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRefCountTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountAltTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java
Labels: 2.x, Bug

#6631 3.x: Update Readme.md with the new package locations
  README.md
Labels: 3.x, Documentation

#6632 3.x: Upgrade Gradle & dependency versions
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/jmh/java/io/reactivex/rxjava3/core/InputWithIncrementingInteger.java
  src/test/java/io/reactivex/rxjava3/disposables/SequentialDisposableTest.java
  src/test/java/io/reactivex/rxjava3/disposables/SerialDisposableTests.java
Labels: 3.x, Build

#6633 3.x: Upgrade to Reactive Streams 1.0.3
  build.gradle
Labels: 3.x, Build

#6635 3.x: Remove vararg overloads for combineLatest in Observable + Flowable
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/test/java/io/reactivex/rxjava3/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableCombineLatestTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableCombineLatestTest.java
  src/test/java/io/reactivex/rxjava3/observable/ObservableNullTests.java
  src/test/java/io/reactivex/rxjava3/tck/CombineLatestArrayDelayErrorTckTest.java
  src/test/java/io/reactivex/rxjava3/tck/CombineLatestArrayTckTest.java
Labels: 3.x, Enhancement

#6637 3.x: Avoid using System.getProperties() due to security restrictions
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Scheduler.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/ComputationScheduler.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/IoScheduler.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/NewThreadScheduler.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/SchedulerPoolFactory.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/SingleScheduler.java
  src/main/java/io/reactivex/rxjava3/schedulers/Schedulers.java
  src/test/java/io/reactivex/rxjava3/internal/schedulers/SchedulerPoolFactoryTest.java
Labels: 3.x

#6638 3.x: Rename zipIterable, remove zip(O(O)), adjust concatMapX arg order
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableInternalHelper.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableInternalHelper.java
  src/test/java/io/reactivex/rxjava3/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableConcatMapSchedulerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableConcatMapTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableConcatTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatMapSchedulerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatMapTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatTest.java
  src/test/java/io/reactivex/rxjava3/observable/ObservableNullTests.java
Labels: 3.x, Cleanup, Removal

#6640 3.x: Rename combineLatest methods that take an array to combineLatestArray
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableCombineLatestTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableCombineLatestTest.java
  src/test/java/io/reactivex/rxjava3/tck/CombineLatestArrayTckTest.java
Labels: 3.x, Cleanup

#6642 3.x: Fix groupBy not canceling upstream due to group abandonment
  .travis.yml
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupBy.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableGroupBy.java
  src/test/java/io/reactivex/rxjava3/flowable/FlowableGroupByTests.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableGroupByTest.java
Labels: 3.x, Shortcoming
