Repository ReactiveX/RxJava, pull requests merged in 2019-09, with the labels that each got.

#6650 3.x: constrain upstream requests from take, remove limit operator
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableLimit.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableTake.java
  src/test/java/io/reactivex/rxjava3/flowable/FlowableSubscriberTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableBufferTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableMergeWithMaybeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableMergeWithSingleTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableTakeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableTakeTest2.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableConcatMapMaybeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableConcatMapSingleTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableSwitchMapMaybeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableSwitchMapSingleTest.java
  src/test/java/io/reactivex/rxjava3/tck/LimitTckTest.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationCheckerTest.java
Labels: 3.x, Enhancement

#6653 2.x: Fix takeLast(time) last events time window calculation.
  src/main/java/io/reactivex/internal/operators/observable/ObservableTakeLastTimed.java
  src/test/java/io/reactivex/TimesteppingScheduler.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableTakeLastTimedTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableTakeLastTimedTest.java
Labels: 2.x, Bug

#6652 3.x: Fix size+time bound window not creating windows properly
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowTimed.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowTimed.java
  src/test/java/io/reactivex/rxjava3/flowable/FlowableWindowTests.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableWindowWithTimeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableWindowWithTimeTest.java
  src/test/java/io/reactivex/rxjava3/observable/ObservableWindowTests.java
Labels: 3.x, Bug

#6657 2.x: Fix size+time bound window not creating windows properly
  src/main/java/io/reactivex/internal/operators/flowable/FlowableWindowTimed.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableWindowTimed.java
  src/test/java/io/reactivex/flowable/FlowableWindowTests.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableWindowWithTimeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableWindowWithTimeTest.java
  src/test/java/io/reactivex/observable/ObservableWindowTests.java
Labels: 2.x, Bug
