Repository ReactiveX/RxJava, pull requests merged in 2019-07, with the labels that each got.

#6556 3.x rename on error resume next methods to disambiguate when calling from kotlin (#6551)
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Maybe.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/Single.java
  src/test/java/io/reactivex/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableDelayTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableOnErrorResumeNextViaFlowableTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowablePublishFunctionTest.java
  src/test/java/io/reactivex/internal/operators/maybe/MaybeOnErrorXTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableDelayTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableOnErrorResumeNextTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableOnErrorResumeWithTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleDelayTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleMiscTest.java
  src/test/java/io/reactivex/internal/operators/single/SingleOnErrorXTest.java
  src/test/java/io/reactivex/maybe/MaybeTest.java
  src/test/java/io/reactivex/observable/ObservableNullTests.java
  src/test/java/io/reactivex/single/SingleNullTests.java
  src/test/java/io/reactivex/tck/OnErrorResumeWithTckTest.java
Labels: 3.x, Cleanup

#6560 2.x Fix NPE when debouncing empty source
  src/main/java/io/reactivex/internal/operators/flowable/FlowableDebounce.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableDebounce.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableDebounceTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableDebounceTest.java
Labels: 2.x, Bug

#6559 3.x Fix NPE when debouncing empty source
  src/main/java/io/reactivex/internal/operators/flowable/FlowableDebounce.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableDebounce.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableDebounceTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableDebounceTest.java
Labels: 3.x, Bug

#6564 3.x: remove buffer/window with supplier & onExceptionResumeNext
  src/main/java/io/reactivex/Flowable.java
  src/main/java/io/reactivex/Observable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferBoundarySupplier.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableOnErrorNext.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableWindowBoundarySupplier.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableBufferBoundarySupplier.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableOnErrorNext.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableWindowBoundarySupplier.java
  src/test/java/io/reactivex/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableOnExceptionResumeNextViaFlowableTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableWindowWithFlowableTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableWindowWithStartEndFlowableTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableBufferTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableOnExceptionResumeNextViaObservableTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableWindowWithObservableTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableWindowWithStartEndObservableTest.java
  src/test/java/io/reactivex/observable/ObservableNullTests.java
  src/test/java/io/reactivex/schedulers/TrampolineSchedulerTest.java
Labels: 3.x, Removal

#6566 3.x: fix wording in Single javadocs
  src/main/java/io/reactivex/Single.java
Labels: 3.x, Documentation

#6565 Fix JavaDocs of Single.doOnTerminate refer to onComplete notification
  src/main/java/io/reactivex/Single.java
Labels: 2.x, Documentation

#6570 3.x: Code verification fixes for javac's generated switchmap classes
  src/test/java/io/reactivex/testsupport/TestHelper.java
  src/test/java/io/reactivex/validators/CheckLocalVariablesInTests.java
  src/test/java/io/reactivex/validators/FixLicenseHeaders.java
  src/test/java/io/reactivex/validators/InternalWrongNaming.java
  src/test/java/io/reactivex/validators/JavadocFindUnescapedAngleBrackets.java
  src/test/java/io/reactivex/validators/JavadocForAnnotations.java
  src/test/java/io/reactivex/validators/JavadocWording.java
  src/test/java/io/reactivex/validators/MaybeNo2Dot0Since.java
  src/test/java/io/reactivex/validators/NewLinesBeforeAnnotation.java
  src/test/java/io/reactivex/validators/NoAnonymousInnerClassesTest.java
  src/test/java/io/reactivex/validators/OperatorsAreFinal.java
  src/test/java/io/reactivex/validators/TestPrefixInMethodName.java
  src/test/java/io/reactivex/validators/TextualAorAn.java
  src/test/java/io/reactivex/validators/TooManyEmptyNewLines.java
Labels: 3.x, Test, Tools

#6572 3.x: fix switchMaps inconsistency swallowing errors when cancelled
  src/main/java/io/reactivex/internal/operators/flowable/FlowableFlatMap.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableSwitchMap.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapCompletable.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapMaybe.java
  src/main/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapSingle.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapCompletable.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapMaybe.java
  src/main/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapSingle.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableFlatMap.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableSwitchMap.java
  src/main/java/io/reactivex/internal/util/AtomicThrowable.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableSwitchTest.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapCompletableTest.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/FlowableSwitchMapSingleTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapCompletableTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapMaybeTest.java
  src/test/java/io/reactivex/internal/operators/mixed/ObservableSwitchMapSingleTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableSwitchTest.java
  src/test/java/io/reactivex/internal/util/AtomicThrowableTest.java
Labels: 3.x, Bug

#6574 3.x: travis use openjdk8 as oraclejdk8 stopped working?
  .travis.yml
Labels: 3.x, Build

#6577 Fix issue #6576 - ObservableBlockingSubscribe compares BlockingObserver.TERMINATED with wrong object
  src/main/java/io/reactivex/internal/operators/observable/ObservableBlockingSubscribe.java
Labels: 3.x, Bug

#6581 3.x: Add more time for GC in RefCountTest.publishNoLeak
  src/test/java/io/reactivex/internal/operators/flowable/FlowableRefCountTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java
Labels: 3.x, Test-Failures

#6579 3.x: widen throws on the XOnSubscribe interfaces
  src/main/java/io/reactivex/CompletableOnSubscribe.java
  src/main/java/io/reactivex/FlowableOnSubscribe.java
  src/main/java/io/reactivex/MaybeOnSubscribe.java
  src/main/java/io/reactivex/ObservableOnSubscribe.java
  src/main/java/io/reactivex/SingleOnSubscribe.java
Labels: 3.x, Enhancement

#6582 3.x: Fix truncation bugs in replay() and ReplaySubject/Processor
  src/main/java/io/reactivex/internal/operators/flowable/FlowableReplay.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableReplay.java
  src/main/java/io/reactivex/processors/ReplayProcessor.java
  src/main/java/io/reactivex/subjects/ReplaySubject.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableReplayEagerTruncateTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableReplayEagerTruncateTest.java
  src/test/java/io/reactivex/processors/ReplayProcessorTest.java
  src/test/java/io/reactivex/subjects/ReplaySubjectTest.java
  src/test/java/io/reactivex/testsupport/TimesteppingScheduler.java
Labels: 3.x, Bug

#6589 Create a base test class and have all unit tests extend it
  src/test/java/io/reactivex/RxJavaTest.java
  src/test/java/io/reactivex/completable/CompletableRetryTest.java
  src/test/java/io/reactivex/completable/CompletableTest.java
  src/test/java/io/reactivex/completable/CompletableTimerTest.java
  src/test/java/io/reactivex/disposables/CompositeDisposableTest.java
  src/test/java/io/reactivex/disposables/DisposablesTest.java
  src/test/java/io/reactivex/disposables/FutureDisposableTest.java
  src/test/java/io/reactivex/disposables/SequentialDisposableTest.java
  src/test/java/io/reactivex/disposables/SerialDisposableTests.java
  src/test/java/io/reactivex/exceptions/CompositeExceptionTest.java
  src/test/java/io/reactivex/exceptions/ExceptionsNullTest.java
  src/test/java/io/reactivex/exceptions/ExceptionsTest.java
  src/test/java/io/reactivex/exceptions/OnErrorNotImplementedExceptionTest.java
  src/test/java/io/reactivex/exceptions/OnNextValueTest.java
Labels: 3.x, Test

#6598 3.x: Fix mergeWith not cancelling the other source if the main errors
  src/main/java/io/reactivex/internal/operators/flowable/FlowableMergeWithCompletable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableMergeWithMaybe.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableMergeWithSingle.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableMergeWithCompletable.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableMergeWithMaybe.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableMergeWithSingle.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithCompletableTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithMaybeTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithSingleTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithCompletableTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithMaybeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithSingleTest.java
Labels: 3.x, Bug

#6599 2.x: Fix mergeWith not canceling other when the main fails
  .travis.yml
  src/main/java/io/reactivex/internal/operators/flowable/FlowableMergeWithCompletable.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableMergeWithMaybe.java
  src/main/java/io/reactivex/internal/operators/flowable/FlowableMergeWithSingle.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableMergeWithCompletable.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableMergeWithMaybe.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableMergeWithSingle.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithCompletableTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithMaybeTest.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableMergeWithSingleTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithCompletableTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithMaybeTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableMergeWithSingleTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountAltTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableRefCountTest.java
Labels: 2.x, Bug

#6601 2.x: ObservableBlockingSubscribe compares with wrong object
  src/main/java/io/reactivex/internal/operators/observable/ObservableBlockingSubscribe.java
Labels: 2.x, Bug

#6602 2.x: Fix truncation bugs in replay() and ReplaySubject/Processor
  src/main/java/io/reactivex/internal/operators/flowable/FlowableReplay.java
  src/main/java/io/reactivex/internal/operators/observable/ObservableReplay.java
  src/main/java/io/reactivex/processors/ReplayProcessor.java
  src/main/java/io/reactivex/subjects/ReplaySubject.java
  src/test/java/io/reactivex/TimesteppingScheduler.java
  src/test/java/io/reactivex/processors/ReplayProcessorTest.java
  src/test/java/io/reactivex/subjects/ReplaySubjectTest.java
Labels: 2.x, Bug
