Repository ReactiveX/RxJava, pull requests merged in 2020-12, with the labels that each got.

#7126 3.x: Improve error messages in the test consumers
  src/main/java/io/reactivex/rxjava3/observers/BaseTestConsumer.java
  src/test/java/io/reactivex/rxjava3/observers/TestObserverTest.java
  src/test/java/io/reactivex/rxjava3/subscribers/TestSubscriberTest.java
Labels: 3.x, Enhancement, Test

#7127 3.x: Improve Javadocs of Connectable sources
  src/main/java/io/reactivex/rxjava3/flowables/ConnectableFlowable.java
  src/main/java/io/reactivex/rxjava3/observables/ConnectableObservable.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocCodesAndLinks.java
Labels: 3.x, Cleanup, Documentation

#7124 3.x: Add onBackpressureReduce operator
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/AbstractBackpressureThrottlingSubscriber.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureLatest.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureReduce.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureLatestTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureReduceTest.java
Labels: 3.x, Feature-Request
