Repository ReactiveX/RxJava, pull requests merged in 2020-09, with the labels that each got.

#7071 3.x: fromRunnable/fromAction javadoc improvements
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
Labels: 3.x, Cleanup, Documentation

#7073 3.x: Patch out duplicate @NonNull annotation in generated javadocs
  gradle/javadoc_cleanup.gradle
Labels: 3.x, Documentation

#7080 Change a method name to make consistent with PR#6801
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableZipIterable.java
Labels: 3.x, Cleanup

#7084 2.x: Fix toFlowable(ERROR) not cancelling upon MBE
  src/main/java/io/reactivex/internal/operators/flowable/FlowableOnBackpressureError.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableOnBackpressureErrorTest.java
Labels: 2.x, Bug

#7083 3.x: Fix toFlowable(ERROR) not cancelling on MBE
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureError.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureErrorTest.java
Labels: 3.x, Bug
