Repository ReactiveX/RxJava, pull requests merged in 2020-07, with the labels that each got.

#7023 [Wiki] Edit dependency for gradle
  docs/Getting-Started.md
Labels: Documentation

#7028 3.x: Allow MBE in FlowableGroupByTest.issue6974RunPart2NoEvict
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
Labels: 3.x, Test-Failures

#7040 3.x: Fix map() conditional chain causing NPE
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableMap.java
  src/test/java/io/reactivex/rxjava3/internal/jdk8/FlowableMapOptionalTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableMapTest.java
Labels: 3.x, Bug

#7033 {Flowable,Observable}.collect(Collector) contravariant on T
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableCollectWithCollector.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/FlowableCollectWithCollectorSingle.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/ObservableCollectWithCollector.java
  src/main/java/io/reactivex/rxjava3/internal/jdk8/ObservableCollectWithCollectorSingle.java
Labels: 3.x, Enhancement
