Repository ReactiveX/RxJava, pull requests merged in 2020-05, with the labels that each got.

#6975 3.x: Fix Flowable.groupBy eviction logic double decrement and hang
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupBy.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
Labels: 3.x, Bug

#6979 3.x: Fix Flowable.groupBy cancellation/cleanup/eviction race hangs
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupBy.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
Labels: 3.x, Bug

#6983 3.x: Disable fusion on the groups of Flowable.groupBy
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupBy.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
Labels: 3.x, Bug

#6990 Add missing `@Test` annotation
  src/test/java/io/reactivex/rxjava3/subjects/ReplaySubjectTest.java
Labels: 3.x, Cleanup, Test

#6992 Removed unnecessary upstream.cancel() call for casually finished upstream sequences.
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowablePublishMulticast.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowablePublishFunctionTest.java
Labels: 3.x, Cleanup

#6988 3.x: Fix Flowable.groupBy eviction-completion-replenishment problems
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupBy.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
Labels: 3.x, Bug

#6994 3.x: Fix recent groupBy tests sometimes failing with MBE
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
Labels: 3.x, Test-Failures

#6997 Fixed image link and added java examples for Connectable Observable operators
  docs/Connectable-Observable-Operators.md
  docs/Getting-Started.md
Labels: 3.x, Documentation

#7000 3.x update Conditional-and-Boolean-Operators.md
  docs/Conditional-and-Boolean-Operators.md
Labels: 3.x, Documentation
