Repository ReactiveX/RxJava, pull requests merged in 2020-04, with the labels that each got.

#6944 Update image urls to non-transparent version.
  docs/Backpressure.md
  docs/Blocking-Observable-Operators.md
  docs/Connectable-Observable-Operators.md
  docs/How-To-Use-RxJava.md
  docs/Phantom-Operators.md
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/flowables/ConnectableFlowable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/BlockingFlowableMostRecent.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/BlockingFlowableNext.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/BlockingObservableMostRecent.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/BlockingObservableNext.java
  src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleFlatMapPublisher.java
  src/main/java/io/reactivex/rxjava3/observables/ConnectableObservable.java
  src/main/java/io/reactivex/rxjava3/subjects/BehaviorSubject.java
Labels: 3.x, Documentation

#6946 3.x: Fix Observable.flatMap with maxConcurrency hangs
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableFlatMap.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableFlatMapTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableFlatMapTest.java
Labels: 3.x, Bug

#6953 3.x: Workaround flakyness of multiThreadedWithNPE* tests
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableSerializeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableSerializeTest.java
Labels: 3.x, Test-Failures

#6943 docs: Quick Javadoc fixes.
  src/main/java/io/reactivex/rxjava3/internal/fuseable/FuseToFlowable.java
  src/main/java/io/reactivex/rxjava3/internal/fuseable/FuseToMaybe.java
  src/main/java/io/reactivex/rxjava3/internal/fuseable/FuseToObservable.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/SchedulerWhen.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/BlockingFlowableNextTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/BlockingObservableNextTest.java
  src/test/java/io/reactivex/rxjava3/observers/SerializedObserverTest.java
  src/test/java/io/reactivex/rxjava3/subscribers/SerializedSubscriberTest.java
  src/test/java/io/reactivex/rxjava3/tck/BaseTck.java
Labels: 3.x, Documentation

#6960 2.x: Fix Observable.flatMap with maxConcurrency hangs (#6947)
  src/main/java/io/reactivex/internal/operators/observable/ObservableFlatMap.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableFlatMapTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableFlatMapTest.java
Labels: 2.x, Bug

#6969 3.x: Allow setting the drift tolerance timeunit via system property
  src/main/java/io/reactivex/rxjava3/core/Scheduler.java
  src/test/java/io/reactivex/rxjava3/core/SchedulerTest.java
Labels: 3.x, Enhancement
