Repository ReactiveX/RxJava, pull requests merged in 2020-01, with the labels that each got.

#6809 3.x: Improve Javadocs of Completable and some others
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/disposables/Disposable.java
  src/main/java/io/reactivex/rxjava3/flowables/ConnectableFlowable.java
  src/main/java/io/reactivex/rxjava3/observables/ConnectableObservable.java
  src/main/java/io/reactivex/rxjava3/processors/BehaviorProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/MulticastProcessor.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocCodesAndLinks.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocWording.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationNaming.java
Labels: 3.x, Cleanup, Documentation

#6812 3.x: Improve Javadocs of Single
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocCodesAndLinks.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocForAnnotations.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationNaming.java
Labels: 3.x, Cleanup, Documentation

#6813 3.x: Fix Junit 4.13 deprecated API use
  src/test/java/io/reactivex/rxjava3/observers/TestObserverTest.java
  src/test/java/io/reactivex/rxjava3/subscribers/TestSubscriberTest.java
  src/test/java/io/reactivex/rxjava3/testsupport/TestObserverExTest.java
  src/test/java/io/reactivex/rxjava3/testsupport/TestSubscriberExTest.java
Labels: 3.x, Cleanup, Test

#6814 3.x: Remove fromFuture(..., Scheduler) overloads
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableToFutureTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableFromTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableToFutureTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleFromTest.java
  src/test/java/io/reactivex/rxjava3/observable/ObservableNullTests.java
  src/test/java/io/reactivex/rxjava3/single/SingleNullTests.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationCheckerTest.java
Labels: 3.x, Removal

#6817 Deleted Functions.naturalOrder
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/internal/functions/Functions.java
Labels: 3.x, Cleanup

#6815 3.x: Improve JavaDocs of Maybe
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocCodesAndLinks.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationNaming.java
Labels: 3.x, Cleanup, Documentation

#6826 3.x: Fix Flowable.flatMap not canceling the inner sources on outer error
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableFlatMap.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableFlatMapTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableFlatMapTest.java
Labels: 3.x, Bug

#6827 2.x: Fix Flowable.flatMap not canceling the inner sources on outer error
  src/main/java/io/reactivex/internal/operators/flowable/FlowableFlatMap.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableFlatMapTest.java
  src/test/java/io/reactivex/internal/operators/observable/ObservableFlatMapTest.java
Labels: 2.x, Bug

#6831 3.x: Improve JavaDocs of Observable and fix similar issues elsewhere
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableBlockingSubscribe.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableBlockingSubscribe.java
  src/main/java/io/reactivex/rxjava3/parallel/ParallelFlowable.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableSkipLastTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableTakeLastTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableTakeLastTimedTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatMapEagerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableSkipLastTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableTakeLastTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableTakeLastTimedTest.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocCodesAndLinks.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocWording.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationCheckerTest.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationNaming.java
Labels: 3.x, Cleanup, Documentation

#6835 3.x: Cleanup javadoc for parameter validation all around
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Scheduler.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/disposables/CompositeDisposable.java
  src/main/java/io/reactivex/rxjava3/flowables/ConnectableFlowable.java
  src/main/java/io/reactivex/rxjava3/observables/ConnectableObservable.java
  src/main/java/io/reactivex/rxjava3/parallel/ParallelFlowable.java
  src/main/java/io/reactivex/rxjava3/processors/ReplayProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/UnicastProcessor.java
  src/main/java/io/reactivex/rxjava3/subjects/BehaviorSubject.java
  src/main/java/io/reactivex/rxjava3/subjects/ReplaySubject.java
  src/main/java/io/reactivex/rxjava3/subjects/UnicastSubject.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableSkipTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableSkipTest.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocCodesAndLinks.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationCheckerTest.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationNaming.java
Labels: 3.x, Cleanup

#6837 3.x: Remove a pointless Observable.concatMapIterable overload
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatTest.java
Labels: 3.x, Cleanup, Removal

#6838 3.x: Rename to combineLatestArrayDelayError
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableCombineLatestTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableCombineLatestTest.java
  src/test/java/io/reactivex/rxjava3/tck/CombineLatestArrayDelayErrorTckTest.java
Labels: 3.x, Cleanup

#6839 3.x: enable javac parameter saving in class files
  build.gradle
  src/test/java/io/reactivex/rxjava3/validators/ParameterNamesInClassesTest.java
Labels: 3.x, Build

#6843 3.x: Improve wording of operators
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocWording.java
Labels: 3.x, Cleanup, Documentation

#6844 3.x: Remove Maybe.onExceptionResumeNext
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeOnErrorNext.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeOnErrorXTest.java
Labels: 3.x, Cleanup, Removal

#6845 3.x: Add operator matrix wiki + auto-extractor
  docs/Operator-Matrix.md
  docs/_Sidebar.md
  src/test/java/io/reactivex/rxjava3/internal/util/OperatorMatrixGenerator.java
Labels: 3.x, Documentation

#6846 Deleted unnecessary NPE tests
  src/test/java/io/reactivex/rxjava3/completable/CompletableTest.java
  src/test/java/io/reactivex/rxjava3/flowable/FlowableNullTests.java
  src/test/java/io/reactivex/rxjava3/flowable/FlowableTests.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableAndThenCompletableabTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableAndThenTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableCreateTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableDoFinallyTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableFromActionTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableFromCallableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableFromMaybeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableFromObservableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableFromPublisherTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableFromRunnableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableFromSingleTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableFromSupplierTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableCreateTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableDelaySubscriptionOtherTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableDoAfterNextTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableDoFinallyTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableFromIterableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureBufferTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeDelayTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeDoAfterSuccessTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeDoFinallyTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeDoOnTerminateTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFlatMapSingleElementTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFlatMapSingleTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFromActionTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFromCallableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFromCompletableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFromRunnableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFromSingleTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFromSupplierTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableCreateTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableDoAfterNextTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableDoFinallyTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableFromIterableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableSwitchTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleCreateTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleDoAfterSuccessTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleDoAfterTerminateTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleDoFinallyTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleDoOnTerminateTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleFlatMapMaybeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleFlatMapTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleMapTest.java
  src/test/java/io/reactivex/rxjava3/maybe/MaybeCreateTest.java
  src/test/java/io/reactivex/rxjava3/maybe/MaybeTest.java
  src/test/java/io/reactivex/rxjava3/observable/ObservableNullTests.java
  src/test/java/io/reactivex/rxjava3/observable/ObservableTest.java
  src/test/java/io/reactivex/rxjava3/single/SingleNullTests.java
Labels: 3.x, Cleanup, Test

#6848 Official Gradle Wrapper Validation GitHub Action
  .github/workflows/gradle-wrapper-validation.yml
Labels: 3.x, Build

#6847 3.x: Simplify @return sentences in Flowable JavaDocs
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/parallel/ParallelFlowable.java
  src/test/java/io/reactivex/rxjava3/internal/util/OperatorMatrixGenerator.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocWording.java
Labels: 3.x, Cleanup, Documentation

#6853 3.x: Fix method argument naming across types
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/BlockingFlowableMostRecentTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/BlockingObservableMostRecentTest.java
  src/test/java/io/reactivex/rxjava3/internal/util/OperatorArgumentNaming.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationCheckerTest.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationNaming.java
Labels: 3.x, Cleanup

#6856 Rename Single.equals to Single.sequenceEqual
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleEqualsTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleMiscTest.java
Labels: 3.x, Cleanup

#6858 3.x: Verify the use of base interfaces in operator inputs & lambdas
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/test/java/io/reactivex/rxjava3/validators/OperatorsUseInterfaces.java
Labels: 3.x, Cleanup

#6857 3.x: [Wiki] Improve Operator-Matrix with links and notes
  docs/Operator-Matrix.md
  src/test/java/io/reactivex/rxjava3/internal/util/OperatorMatrixGenerator.java
Labels: 3.x, Documentation

#6860 3.x: Add last missing throws tag to JavaDocs
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/internal/util/JavadocNoThrows.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationNaming.java
Labels: 3.x, Cleanup, Documentation

#6862 3.x: Add Maybe/Single/Completable blockingSubscribe
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/observers/BlockingDisposableMultiObserver.java
  src/main/java/io/reactivex/rxjava3/internal/observers/BlockingMultiObserver.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableBlockingSubscribeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeBlockingSubscribeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleBlockingSubscribeTest.java
Labels: 3.x, Enhancement

#6866 3.x: Fix many marbles in Maybe
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
Labels: 3.x, Cleanup, Documentation

#6868 3.x: Add Completable.onErrorResumeWith
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableResumeNextTest.java
Labels: 3.x, Documentation, Enhancement

#6869 3.x: Add Single/Completable retryUntil + marbles
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/completable/CompletableRetryTest.java
  src/test/java/io/reactivex/rxjava3/maybe/MaybeRetryTest.java
  src/test/java/io/reactivex/rxjava3/single/SingleRetryTest.java
Labels: 3.x, Documentation, Enhancement

#6870 3.x: Add Maybe/Single/Completable switchOnNext & switchOnNextDelayError
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableSwitchMapCompletablePublisher.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableSwitchMapMaybePublisher.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableSwitchMapSinglePublisher.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableSwitchOnNextTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeSwitchOnNextTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleSwitchOnNextTest.java
Labels: 3.x, Enhancement

#6871 3.x: Add Maybe.dematerialize
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeDematerialize.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeDematerializeTest.java
Labels: 3.x, Enhancement

#6874 3.x: Add timeInterval & timestamp to M/S
  docs/Operator-Matrix.md
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeTimeInterval.java
  src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleTimeInterval.java
  src/main/java/io/reactivex/rxjava3/schedulers/Timed.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeTimeIntervalTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeTimestampTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleTimeIntervalTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleTimestampTest.java
  src/test/java/io/reactivex/rxjava3/internal/util/OperatorMatrixGenerator.java
  src/test/java/io/reactivex/rxjava3/schedulers/TimedTest.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocWording.java
Labels: 3.x, Enhancement

#6875 3.x: Add Maybe/Completable toFuture
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/observers/FutureMultiObserver.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableToFutureTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeToFutureTest.java
Labels: 3.x, Enhancement

#6876 3.x: Add Single.ofType
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleOfTypeTest.java
  src/test/java/io/reactivex/rxjava3/testsupport/TestHelper.java
Labels: 3.x, Documentation, Enhancement

#6877 3.x: Add doOnLifecycle to Maybe, Single & Completable
  docs/Operator-Matrix.md
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeDoOnLifecycle.java
  src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleDoOnLifecycle.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableDoOnLifecycleTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeDoOnLifecycleTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleDoOnLifecycleTest.java
Labels: 3.x, Enhancement

#6879 3.x: Add concatMapX operators (aliases)
  docs/Operator-Matrix.md
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeConcatMapCompletableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeConcatMapSingleTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeConcatMapTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleConcatMapCompletableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleConcatMapMaybeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleConcatMapTest.java
  src/test/java/io/reactivex/rxjava3/internal/util/OperatorMatrixGenerator.java
Labels: 3.x, Documentation, Enhancement

#6881 3.x: Add various concatXDelayError operators
  docs/Operator-Matrix.md
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableConcatArrayDelayErrorTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableConcatDelayErrorTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeConcatArrayEagerDelayErrorTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleConcatArrayDelayErrorTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleConcatArrayEagerDelayErrorTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleConcatDelayErrorTest.java
  src/test/java/io/reactivex/rxjava3/maybe/MaybeTest.java
Labels: 3.x, Cleanup, Documentation, Enhancement

#6882 3.x: Add Single.mergeArray & mergeArrayDelayError
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/internal/fuseable/CancellableQueueFuseableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleMergeArrayTest.java
Labels: 3.x, Enhancement

#6884 3.x: Add Completable.sequenceEqual
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableSequenceEqualTest.java
Labels: 3.x, Enhancement

#6885 3.x: Add missing startWith overloads
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableStartWithTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableStartWithTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeStartWithTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableStartWithTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleStartWithTest.java
Labels: 3.x, Enhancement

#6887 3.x: Add safeSubscribe to Maybe, Single & Completable
  docs/Operator-Matrix.md
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/observers/SafeCompletableObserver.java
  src/main/java/io/reactivex/rxjava3/internal/observers/SafeMaybeObserver.java
  src/main/java/io/reactivex/rxjava3/internal/observers/SafeSingleObserver.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableSafeSubscribeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeSafeSubscribeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleSafeSubscribeTest.java
  src/test/java/io/reactivex/rxjava3/internal/util/OperatorMatrixGenerator.java
Labels: 3.x, Enhancement

#6888 3.x: Use more appropriate operators when delegating to Flowable ops
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableFlatMapMaybePublisher.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableFlatMapSinglePublisher.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableConcatMapMaybePublisher.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableConcatMapSinglePublisher.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/ObservableConcatMapSingle.java
  src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleInternalHelper.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleInternalHelperTest.java
  src/test/java/io/reactivex/rxjava3/maybe/MaybeTest.java
Labels: 3.x, Cleanup

#6890 3.x: Fix marble dimensions, add program that checks them
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/parallel/ParallelFlowable.java
  src/test/java/io/reactivex/rxjava3/internal/util/MarbleDimensions.java
Labels: 3.x, Cleanup, Documentation

#6891 3.x: Swap Maybe.flatMapSingle and Maybe.flatMapSingleElement
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFlatMapSingle.java
  src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFlatMapSingleElement.java
  src/test/java/io/reactivex/rxjava3/core/XFlatMapTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFlatMapSingleElementTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeFlatMapSingleTest.java
Labels: 3.x, Removal

#6894 2.x: Fix groupBy not requesting more if a group is cancelled with buffered items
  src/main/java/io/reactivex/internal/operators/flowable/FlowableGroupBy.java
  src/test/java/io/reactivex/internal/operators/flowable/FlowableGroupByTest.java
Labels: 2.x, Bug

#6895 3.x: Fix groupBy not requesting more if a group is cancelled w/ items
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupBy.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableGroupByTest.java
Labels: 3.x, Bug

#6897 3.x: Add remaining Maybe marbles (+50)
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
Labels: 3.x, Cleanup, Documentation

#6899 3.x: Add concatEagerDelayError across
  docs/Operator-Matrix.md
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableConcatMapEagerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeConcatEagerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatMapEagerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleConcatEagerTest.java
  src/test/java/io/reactivex/rxjava3/internal/util/MarbleDimensions.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationNaming.java
Labels: 3.x, Cleanup, Documentation, Enhancement
