Repository ReactiveX/RxJava, pull requests merged in 2021-03, with the labels that each got.

#7203 3.x: Fix Schedulers.from to honor interruptibleWorker across methods
  src/main/java/io/reactivex/rxjava3/internal/schedulers/AbstractDirectTask.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/ExecutorScheduler.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/NewThreadWorker.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/ScheduledDirectPeriodicTask.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/ScheduledDirectTask.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/SingleScheduler.java
  src/test/java/io/reactivex/rxjava3/internal/operators/completable/CompletableTimerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableTimerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeTimerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableTimerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleTimerTest.java
  src/test/java/io/reactivex/rxjava3/internal/schedulers/AbstractDirectTaskTest.java
  src/test/java/io/reactivex/rxjava3/internal/schedulers/ScheduledDirectPeriodicTaskTest.java
  src/test/java/io/reactivex/rxjava3/schedulers/ExecutorSchedulerInterruptibleTest.java
Labels: 3.x, Bug

#7206 3.x: Fix wrong reference in Single.flattenStreamAsObservable javadoc
  src/main/java/io/reactivex/rxjava3/core/Single.java
Labels: 3.x, Cleanup, Documentation

#7210 Added Javadoc checks to Checkstyle. Fix violating Javadoc.
  build.gradle
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  config/license/HEADER
  config/license/HEADER_JAVA
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Notification.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/exceptions/CompositeException.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableReplay.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/ScalarXMapZHelper.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableReplay.java
  src/main/java/io/reactivex/rxjava3/internal/util/QueueDrainHelper.java
  src/main/java/io/reactivex/rxjava3/observers/BaseTestConsumer.java
  src/test/java/io/reactivex/rxjava3/exceptions/CompositeExceptionTest.java
  src/test/java/io/reactivex/rxjava3/schedulers/SchedulerTestHelper.java
Labels: 3.x, Cleanup

#7212 3.x: CompositeException.printStackTrace to write directly into PrintStream/PrintWriter
  src/main/java/io/reactivex/rxjava3/exceptions/CompositeException.java
Labels: 3.x, Bug

#7213 Fix intermittently failing unit tests
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableConcatMapSchedulerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableConcatTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableMergeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableSubscribeOnTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatMapSchedulerTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableConcatTest.java
  src/test/java/io/reactivex/rxjava3/subjects/UnicastSubjectTest.java
Labels: 3.x, Test-Failures

#7219 Modernize gradle plugin block, change maven to maven-publish
  build.gradle
Labels: 3.x, Build
