Repository ReactiveX/RxJava, pull requests merged in 2021-01, with the labels that each got.

#7144 3.x: Update marbles of amb(), ambArray() and ambWith()
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
Labels: 3.x, Documentation

#7145 3.x: Fix take() mentioning the old limit() operator
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
Labels: 3.x, Cleanup, Documentation

#7151 3.x: onReduceBackpressure internals cleanup
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureReduce.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureReduceWith.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureReduceTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableOnBackpressureReduceWithTest.java
Labels: 3.x, Cleanup, Test

#7150 3.x: Document Schedulers.from's RejectedExecutionException handling
  src/main/java/io/reactivex/rxjava3/schedulers/Schedulers.java
Labels: 3.x, Documentation

#7160 Io Scheduler, Scheduled worker release.
  src/main/java/io/reactivex/rxjava3/internal/schedulers/IoScheduler.java
  src/main/java/io/reactivex/rxjava3/schedulers/Schedulers.java
  src/test/java/io/reactivex/rxjava3/internal/schedulers/IoScheduledReleaseTest.java
Labels: 3.x, Enhancement

#7162 Io Scheduler, Scheduled worker release (v2.x)
  src/main/java/io/reactivex/internal/schedulers/IoScheduler.java
  src/main/java/io/reactivex/schedulers/Schedulers.java
  src/test/java/io/reactivex/internal/schedulers/IoScheduledReleaseTest.java
Labels: 2.x, Enhancement

#7164 Updating documentation for scheduleActual method
  src/main/java/io/reactivex/rxjava3/internal/schedulers/NewThreadWorker.java
Labels: 3.x, Cleanup, Documentation

#7163 3.x: TestScheduler option to use onSchedule hook
  src/main/java/io/reactivex/rxjava3/schedulers/Schedulers.java
  src/main/java/io/reactivex/rxjava3/schedulers/TestScheduler.java
  src/test/java/io/reactivex/rxjava3/schedulers/TestSchedulerTest.java
Labels: 3.x, Enhancement

#7168 3.x: Improve Javadocs style of Schedulers
  src/main/java/io/reactivex/rxjava3/schedulers/Schedulers.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocCodesAndLinks.java
Labels: 3.x, Cleanup, Documentation

#7165 3.x: Add fusion support to concatMap{Maybe|Single|Completable}
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/ConcatMapXMainObserver.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/ConcatMapXMainSubscriber.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableConcatMapCompletable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableConcatMapMaybe.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableConcatMapSingle.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/ObservableConcatMapCompletable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/ObservableConcatMapMaybe.java
  src/main/java/io/reactivex/rxjava3/internal/operators/mixed/ObservableConcatMapSingle.java
  src/main/java/io/reactivex/rxjava3/internal/subscriptions/DeferredScalarSubscription.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableConcatMapCompletableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableConcatMapMaybeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/FlowableConcatMapSingleTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/ObservableConcatMapCompletableTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/ObservableConcatMapMaybeTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/mixed/ObservableConcatMapSingleTest.java
  src/test/java/io/reactivex/rxjava3/testsupport/TestHelper.java
Labels: 3.x, Enhancement

#7169 3.x: Introduce property rx3.scheduler.use-nanotime
  src/main/java/io/reactivex/rxjava3/core/Scheduler.java
  src/main/java/io/reactivex/rxjava3/schedulers/Schedulers.java
  src/test/java/io/reactivex/rxjava3/core/SchedulerTest.java
Labels: 3.x, Enhancement

#7170 2.x: Introduce property rx2.scheduler.use-nanotime (#7154)
  src/main/java/io/reactivex/Scheduler.java
  src/main/java/io/reactivex/schedulers/Schedulers.java
  src/test/java/io/reactivex/SchedulerTest.java
Labels: 2.x, Enhancement
