Repository ReactiveX/RxJava, pull requests merged in 2021-08, with the labels that each got.

#7306 3.x: Add RxJavaPlugins.createExecutorScheduler
  src/main/java/io/reactivex/rxjava3/plugins/RxJavaPlugins.java
  src/main/java/io/reactivex/rxjava3/schedulers/Schedulers.java
Labels: 3.x, Enhancement

#7307 Bump gradle to 7.1.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: 3.x, Build

#7314 Update gradle 7.2
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: Build, 3.x

#7328 3.x: Fix javadoc wording of {Publish|Behavior}Processor::offer()
  gradle/javadoc_cleanup.gradle
  src/main/java/io/reactivex/rxjava3/processors/BehaviorProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/PublishProcessor.java
Labels: Documentation, 3.x
