Repository ReactiveX/RxJava, pull requests merged in 2021-02, with the labels that each got.

#7173 3.x: Workaround for FutureTask.toString + JDK 11 build
  .github/workflows/gradle_jdk11.yml
  src/main/java/io/reactivex/rxjava3/internal/schedulers/AbstractDirectTask.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/ScheduledDirectPeriodicTask.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/ScheduledRunnable.java
  src/test/java/io/reactivex/rxjava3/internal/schedulers/AbstractDirectTaskTest.java
  src/test/java/io/reactivex/rxjava3/internal/schedulers/ScheduledRunnableTest.java
  src/test/java/io/reactivex/rxjava3/schedulers/AbstractSchedulerTests.java
Labels: 3.x, Shortcoming

#7176 3.x: Allow reruns of release actions by enabling bintray.override
  build.gradle
Labels: 3.x, Build

#7178 Fix the typos
  src/main/java/io/reactivex/rxjava3/schedulers/Schedulers.java
Labels: 3.x, Cleanup, Documentation

#7181 3.x: Release to Sonatype directly
  .github/workflows/gradle_release.yml
  build.gradle
  gradle.properties
  gradle/javadoc_cleanup.gradle
Labels: 3.x, Build

#7184 3.x: Upgrade to Gradle 6.8.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: 3.x, Build

#7191 3.x: Add onSubscribe hook to ParallelFlowable operators
  src/main/java/io/reactivex/rxjava3/core/Scheduler.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelCollect.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelConcatMap.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelDoOnNextTry.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelFilter.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelFilterTry.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelFlatMap.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelFlatMapIterable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelFromArray.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelFromPublisher.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelMap.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelMapTry.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelPeek.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelReduce.java
  src/main/java/io/reactivex/rxjava3/internal/operators/parallel/ParallelRunOn.java
  src/main/java/io/reactivex/rxjava3/plugins/RxJavaPlugins.java
  src/test/java/io/reactivex/rxjava3/plugins/RxJavaPluginsTest.java
Labels: 3.x

#7196 3.x: Allow Single.zip and Maybe.zip result to be garbage collected
  src/main/java/io/reactivex/rxjava3/internal/operators/maybe/MaybeZipArray.java
  src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleZipArray.java
Labels: 3.x, Bug
