Repository ReactiveX/RxJava, pull requests merged in 2021-07, with the labels that each got.

#7289 3.x: Update withLatestFrom doc about upstream early complete
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
Labels: 3.x, Documentation

#7293 Removes the purge thread in favour of standard ScheduledThreadPoolExecutor APIs
  src/main/java/io/reactivex/rxjava3/internal/schedulers/SchedulerPoolFactory.java
  src/main/java/io/reactivex/rxjava3/schedulers/Schedulers.java
  src/test/java/io/reactivex/rxjava3/internal/schedulers/SchedulerPoolFactoryTest.java
  src/test/java/io/reactivex/rxjava3/schedulers/ExecutorSchedulerTest.java
Labels: 3.x, Android, Enhancement

#7296 3.x: API promotions for 3.1.0
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/SchedulerPoolFactory.java
  src/main/java/io/reactivex/rxjava3/plugins/RxJavaPlugins.java
  src/main/java/io/reactivex/rxjava3/schedulers/TestScheduler.java
  src/test/java/io/reactivex/rxjava3/internal/schedulers/SchedulerPoolFactoryTest.java
Labels: 3.x, API promotion

#7298 3.x: Add subscribe with disposable container
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/observers/AbstractDisposableAutoRelease.java
  src/main/java/io/reactivex/rxjava3/internal/observers/DisposableAutoReleaseMultiObserver.java
  src/main/java/io/reactivex/rxjava3/internal/observers/DisposableAutoReleaseObserver.java
  src/main/java/io/reactivex/rxjava3/internal/subscribers/DisposableAutoReleaseSubscriber.java
  src/test/java/io/reactivex/rxjava3/internal/observers/CompletableConsumersTest.java
  src/test/java/io/reactivex/rxjava3/internal/observers/MaybeConsumersTest.java
  src/test/java/io/reactivex/rxjava3/internal/observers/ObservableConsumersTest.java
  src/test/java/io/reactivex/rxjava3/internal/observers/SingleConsumersTest.java
  src/test/java/io/reactivex/rxjava3/internal/subscribers/FlowableConsumersTest.java
  src/test/java/io/reactivex/rxjava3/validators/BaseTypeAnnotations.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocForAnnotations.java
  src/test/java/io/reactivex/rxjava3/validators/JavadocWording.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationCheckerTest.java
Labels: 3.x, Enhancement

#7301 3.x: Javadocs fix some wording in Schedulers.java
  src/main/java/io/reactivex/rxjava3/schedulers/Schedulers.java
Labels: 3.x, Documentation

#7302 Fix missing NonNull on Observable.map
  src/main/java/io/reactivex/rxjava3/core/Observable.java
Labels: 3.x, Cleanup

#7303 3.x: Move nullability annotations into the type argument declaration
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
  src/main/java/io/reactivex/rxjava3/internal/subscriptions/BasicIntQueueSubscription.java
  src/main/java/io/reactivex/rxjava3/internal/subscriptions/DeferredScalarSubscription.java
  src/main/java/io/reactivex/rxjava3/parallel/ParallelFlowable.java
  src/main/java/io/reactivex/rxjava3/plugins/RxJavaPlugins.java
  src/main/java/io/reactivex/rxjava3/processors/AsyncProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/BehaviorProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/MulticastProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/PublishProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/ReplayProcessor.java
  src/main/java/io/reactivex/rxjava3/processors/UnicastProcessor.java
  src/main/java/io/reactivex/rxjava3/subscribers/SafeSubscriber.java
  src/test/java/io/reactivex/rxjava3/validators/NonNullMethodTypeArgumentCheck.java
  src/test/java/io/reactivex/rxjava3/validators/SourceAnnotationCheck.java
Labels: 3.x, Cleanup
