Repository ReactiveX/RxJava, pull requests merged in 2022-06, with the labels that each got.

#7436 3.x: Add missing `@NonNull` annotation to `Maybe` type argument
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
Labels: Cleanup, 3.x

#7437 feat: add support for Remote Cloud Development with Gitpod
  .gitpod.yml
  README.md
Labels: Tools

#7438 3.x: Remove redundant interface declarations
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableBufferExactBoundary.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableObserveOn.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableToList.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableBufferExactBoundary.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/NewThreadWorker.java
  src/main/java/io/reactivex/rxjava3/internal/schedulers/TrampolineScheduler.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationCheckerTest.java
Labels: Cleanup, 3.x

#7442 3.x: Fix formatting in TestObserver/Consumer/Subscriber javadoc html
  gradle/javadoc_cleanup.gradle
Labels: Documentation, Cleanup, 3.x
