Repository ReactiveX/RxJava, pull requests merged in 2022-08, with the labels that each got.

#7456 3.x: Upgrade to Gradle 7.5.1
  gradle/wrapper/gradle-wrapper.properties
Labels: Build, 3.x

#7457 3.x: Add onDropped callback to throttleLatest operator
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableThrottleLatest.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableThrottleLatest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableThrottleLatestTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableThrottleLatestTest.java
  src/test/java/io/reactivex/rxjava3/testsupport/TestHelper.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationCheckerTest.java
Labels: Enhancement, 3.x

#7460 3.x: Update Flowable.throttleLatest MissingBackpressureException message
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableThrottleLatest.java
Labels: Cleanup, 3.x

#7463 Error in javadoc generation due wrong tag name
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
Labels: Documentation, Cleanup, 3.x
