Repository ReactiveX/RxJava, pull requests merged in 2023-01, with the labels that each got.

#7508 3.x: Fix fromCompletionStage javadoc
  src/main/java/io/reactivex/rxjava3/core/Completable.java
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Maybe.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/core/Single.java
Labels: Documentation, Cleanup, 3.x

#7510 Add onDropped callback for throttleWithTimeout - #7458
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableDebounceTimed.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableDebounceTimed.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableDebounceTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableDebounceTest.java
  src/test/java/io/reactivex/rxjava3/validators/ParamValidationCheckerTest.java
Labels: Enhancement, 3.x

#7511 3.x: ThrottleWithTimeout+Consumer cleanup
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
  src/main/java/io/reactivex/rxjava3/core/Observable.java
  src/main/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableDebounceTimed.java
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableDebounceTimed.java
Labels: Cleanup, 3.x

#7515 3.x: Fix Single.timeout race condition
  src/main/java/io/reactivex/rxjava3/internal/operators/single/SingleTimeout.java
  src/test/java/io/reactivex/rxjava3/internal/operators/single/SingleTimeoutTest.java
Labels: Bug, 3.x

#7519 Remove obsolete JFrog references in README.md
  README.md
Labels: Documentation, 3.x
