Repository ReactiveX/RxJava, pull requests merged in 2023-03, with the labels that each got.

#7534 Change summary to caption, because summary is obsolete in HTML5
  src/main/java/io/reactivex/rxjava3/observers/package-info.java
  src/main/java/io/reactivex/rxjava3/subjects/package-info.java
Labels: Documentation, Cleanup

#7535 3.x: Try using https to access the reactive streams javadoc
  build.gradle
Labels: Documentation, 3.x

#7541 Add minimum GitHub token permissions for workflows
  .github/workflows/gradle_release.yml
  .github/workflows/gradle_snapshot.yml
Labels: Build
