Repository ReactiveX/RxJava, pull requests merged in 2023-08, with the labels that each got.

#7590 Remove `@NonNull` annotation from `Collector` container type parameter.
  src/main/java/io/reactivex/rxjava3/core/Flowable.java
Labels: Cleanup, 3.x

#7594 Hash-pin GitHub Actions
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/gradle_branch.yml
  .github/workflows/gradle_jdk11.yml
  .github/workflows/gradle_pr.yml
  .github/workflows/gradle_release.yml
  .github/workflows/gradle_snapshot.yml
Labels: Build, 3.x

#7597 3.x: Fix ObservableSwitchMap NPE due to onSubscribe-cancel race
  src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableSwitchMap.java
  src/test/java/io/reactivex/rxjava3/internal/operators/flowable/FlowableSwitchTest.java
  src/test/java/io/reactivex/rxjava3/internal/operators/observable/ObservableSwitchTest.java
Labels: Bug, 3.x
